namespace Dziekanowka.Mechanizm
{
    public enum EkranGry
    {
        Start,
        Gospodarstwo,
        Rzeznia,
        Zwierzyniec,
        Kurnik,
        Gesiarnia,
        Indyczarnia,
        Kacznik,
        Krolikarnia,
        Chlew,
        Owczarnia,
        Alpakarium,
        Koziarnia,
        Obora,
        Stajnia,
        ZaBrama,
        GarazGospodarczy,
        Studnia,
        Sklepik,
        SklepikOwoce,
        SklepikWarzywa,
        PoleIntro,
        Pole1,
        Pole2,
        Sad1,
        Sad2,
        Zboze,
        AnimacjaTraktora,
        AnimacjaTraktoraPowrot,
        CzyszczeniePola,
        CzyszczenieDrzewa,
        KoszenieTrawy,
        PsySasiadaSzczekaja
    }
}