namespace Dziekanowka.Mechanizm
{
    public class Fiszki
    {
        private static string[,] numbers = {{"zero","jeden","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć","dziesięć","jedenaście","dwanaście","trzynaście","czternaście","piętnaście","szesnaście","siedemnaście","osiemnaście","dziewiętnaście","dwadzieścia","trzydzieści","czterdzieści","pięćdziesiąt","sześćdziesiąt","siedemdziesiąt","osiemdziesiąt", "dziewięćdziesiąt","sto","tysiąc","milion","połowa","numer","metr" },
                                            {"zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty", "thirty","forty","fifty","sixty","seventy","eighty","ninety","hundred","thousand","million","half","number","metre"},
                                            {"cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve","diez","once","doce","trece","catorce","quince","dieciséis","diecisiete","dieciocho","diecinueve","veinte","treinta","cuarenta","cincuenta","sesenta","setenta","ochenta","noventa","cien","mil","el millón","la mitad","el número","el metro"}};
        private static string[,] colors = {{"czarny","biały","czerwony","żółty","zielony","niebieski","szary","różowy","pomarańczowy","brązowy","fioletowy","duży","mały","długi","kolor","okrągły","złoty","srebrny","kwadratowy","kształt"},
                                           {"black","white","red","yellow","green","blue","grey","pink","orange","brown","purple","big","small","long","colour","round","gold","silver","square","shape"},
                                           {"negro","blanco","rojo","amarillo","verde","azul","gris","rosa","naranja","marrón","morado","grande","pequeño","largo","el color","redondo","dorado","plateado","cuadrado","la forma"}};
        private static string[,] animals = {{"zwierzak domowy","zwierzę","kot","pies","ryba","chomik","krowa","koń","kaczka","osioł","małpa","ptak","papuga","kurczak","ślimak","motyl","mucha","lew","mysz","słoń","pszczoła","wilk","lis","królik","komar","żaba","świnia","tygrys","owca" },
                                            {"pet","animal","cat","dog","fish","hamster","cow","horse","duck","donkey", "monkey","bird","parrot","chicken","snail","butterfly","fly","lion","mouse","elephant","bee","wolf","fox","rabbit","mosquito","frog","pig","tiger","sheep" },
                                            {"la mascota","el animal","el gato","el perro","el pez","el hámster","la vaca","el caballo","el pato","el burro","el mono","el pájaro","el loro","la gallina","el caracol","la mariposa","la mosca","el león","el ratón","el elefante","la abeja","el lobo","el zorro","el conejo","el mosquito","la rana","el cerdo","el tigre","la oveja"}};
        private static string[,] time = {{"czas","noc","rano","popołudnie","wieczór","pora roku","rok","miesiąc","tydzień","dzień","godzina","minuta","sekunda","poniedziałek","wtorek","środa","czwartek","piątek","sobota","niedziela","styczeń","luty","marzec","kwiecień","maj","czerwiec","lipiec","sierpień","wrzesień","październik","listopad","grudzień","wiosna", "lato","jesień","zima","dzisiaj","wczoraj","jutro","następny","codziennie","nigdy"},
                                         {"time","night","morning","afternoon","evening","season","year","month","week","day","hour", "minute","second","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday","January","February","March","April","May","June","July","August","September","October", "November","December","spring","summer","autumn","winter","today","yesterday","tomorrow","next","every day","never"},
                                         {"el tiempo","la noche","la mañana","la tarde","el atardecer","la estación","el año","el mes","la semana","el día","la hora","el minuto","el segundo","el lunes","el martes","el miércoles","el jueves","el viernes","el sábado","el domingo","enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre","la primavera","el verano","el otoño","el invierno","hoy","ayer","mañana","siguiente","todos los días","nunca"}};
        private static string[,] family = {{"rodzina","ojciec","matka","córka","syn","wujek","ciocia","brat","siostra","babcia","dziadek","rodzic","mężczyzna","kobieta","mąż","żona","dziecko","chłopiec","dziewczynka","kuzyn","chłopak (sympatia)","dziewczyna (sympatia)","rozwiedziony","żonaty/mężatka","ślub","być razem","wdowa","przyjaciel","urodzić się"},
                                           {"family","father","mother","daughter","son","uncle","aunt","brother","sister","grandmother","grandfather","parent","man","woman","husband","wife","child","boy","girl","cousin", "boyfriend","girlfriend","divorced","married","wedding","be together","widow","friend","be born"},
                                           {"la familia","el padre","la madre","la hija","el hijo","el tío","la tía","el hermano","la hermana","la abuela","el abuelo","el padre/la madre","el hombre","la mujer","el marido","la esposa","el niño","el niño","la niña","el primo","el novio","la novia","divorciado","casado/casada","la boda","estar juntos","la viuda","el amigo","nacer"}};
        private static string[,] home = {{"klucz","pokój","lodówka","salon","sypialnia","łazienka","kuchnia","szafa","książka","regał","pralka","zlew","prysznic","wanna","stół","krzesło","łóżko","kanapa","okno","ściana","podłoga","parter","drzwi","sufit","dywan","otwierać","zamykać","garaż","piwnica","lustro","adres","dom","mieszkanie","zasłony"},
                                         {"key","room","fridge","living room","bedroom","bathroom","kitchen","wardrobe","book","bookshelf","washing machine","sink","shower","bathtub","table","chair","bed", "sofa","window","wall","floor","ground floor","door","ceiling","carpet","open","close","garage","cellar","mirror","address","house","flat","curtains"},
                                         {"la llave","la habitación","la nevera","el salón","el dormitorio","el baño","la cocina","el armario","el libro","la estantería","la lavadora","el fregadero","la ducha","la bañera","la mesa","la silla","la cama","el sofá","la ventana","la pared","el suelo","la planta baja","la puerta","el techo","la alfombra","abrir","cerrar","el garaje","el sótano","el espejo","la dirección","la casa","el piso","las cortinas"}};
        private static string[,] tournee = {{"wycieczka","rower","prom","lotnisko","przystanek autobusowy","metro","bagaż","turysta","lot","jechać samochodem","wracać","autobus","pociąg","samochód","samolot","(po)wolny","szybki","skręcać","gubić","bilet","paszport","dworzec","iść","w lewo","w prawo","prosto","na rogu","przejście dla pieszych","skrzyżowanie","zakręt","róg (ulicy)","znak drogowy","chodnik"},
                                            {"trip","bike","ferry","airport","bus stop","underground","luggage","tourist","flight","drive","come back","bus","train","car","plane","slow","fast","turn","lose","ticket","passport","station","go","left","right","straight ahead","on the corner","pedestrian crossing","crossroads","turn","corner (street)","road sign","pavement"},
                                            {"el viaje","la bicicleta","el ferry","el aeropuerto","la parada de autobús","el metro","el equipaje","el/la turista","el vuelo","conducir","volver","el autobús","el tren","el coche","el avión","lento","rápido","girar","perder","el billete","el pasaporte","la estación","ir","a la izquierda","a la derecha","todo recto","en la esquina","el paso de peatones","el cruce","la curva","la esquina","la señal de tráfico","la acera"} };
        private static string[,] food = {{"jabłko","banan","pomidor","ziemniak","marchewka","cebula","czosnek","ogórek","mięso","ryż","ryba","kurczak","makaron","chleb","śliwka","gruszka", "brzoskwinia","pomarańcza","cytryna","jajko","mleko","sok","herbata","woda","kawa","śniadanie","obiad","kolacja","truskawka","jagoda","malina","jeść","pić","owoc","warzywo","ciasto","głodny","spragniony","sól","deser","ser żółty","masło","zupa","jedzenie","gotować"},
                                         {"apple","banana","tomato","potato","carrot","onion","garlic","cucumber","meat","rice","fish","chicken","pasta","bread","plum","pear","peach","orange","lemon","egg","milk","juice","tea","water","coffee","breakfast","dinner","supper","strawberry","berry","raspberry","eat","drink","fruit","vegetable","cake","hungry","thirsty","salt","dessert","cheese","butter","soup","food","cook"},
                                         {"la manzana","el plátano","el tomate","la patata","la zanahoria","la cebolla","el ajo","el pepino","la carne","el arroz","el pescado","el pollo","la pasta","el pan","la ciruela","la pera","el melocotón","la naranja","el limón","el huevo","la leche","el zumo","el té","el agua","el café","el desayuno","la comida","la cena","la fresa","la baya","la frambuesa","comer","beber","la fruta","la verdura","el pastel","hambriento","sediento","la sal","el postre","el queso","la mantequilla","la sopa","la comida","cocinar"}};
        private static string[,] speak = {{"imię","nad","obok","pomiędzy","przed","ale","też","pod","w","na","za","i, oraz","do widzenia","dziękuję","Jak się masz?","dobry wieczór","dzień dobry (przed południem)","dzień dobry (po południu)","przepraszam (za coś)","przepraszam (z zapytaniem)","proszę (o coś)","ja","ty (wy)","to","on","ona","my","oni (one)","tak","nie","mieć","dobry","cześć","zły","chcieć","brać","robić (np. ciasto, zupę)","wspaniały","Ile? (policzalne)","Kto?","Co?","znać, wiedzieć","Gdzie?","Jak?","mówić, przemawiać","nie ma za co","Dlaczego?","mieszkać","być","robić (np. zakupy, ćwiczenie)","Ile? (niepoliczalne)","Kiedy?","dawać","zgadzać się","nie zgadzać się","moim zdaniem","myślę, że","mieć rację","mylić się","według mnie","zgoda!","masz rację","to zależy"},
                                          {"name","over","next to","between","in front of","but","too","under","in","on","behind","and","goodbye","thank you","How are you?","good evening","good morning","good afternoon","sorry","excuse me","please","I","you","it","he","she","we","they","yes","no","have","good","hello","bad","want","take","make","great","How many?","Who?","What?","know","Where?","How?","speak","you are welcome","Why?","live","be","do","How much?","When?","give","agree","disagree","in my opinion","I think that","be right","be wrong","in my view","agreed!","you're right","it depends"},
                                          {"el nombre","encima de","al lado de","entre","delante de","pero","también","debajo de","en","en","detrás de","y","adiós","gracias","¿Cómo estás?","buenas noches","buenos días","buenas tardes","lo siento","perdón","por favor","yo","tú (vosotros)","eso","él","ella","nosotros","ellos (ellas)","sí","no","tener","bueno","hola","malo","querer","tomar","hacer","genial","¿Cuántos?","¿Quién?","¿Qué?","saber","¿Dónde?","¿Cómo?","hablar","de nada","¿Por qué?","vivir","ser","hacer","¿Cuánto?","¿Cuándo?","dar","estar de acuerdo","no estar de acuerdo","en mi opinión","creo que","tener razón","equivocarse","desde mi punto de vista","¡de acuerdo!","tienes razón","depende"} };
        private static string[,] city = {{"ogród","droga","park","pole","stolica","ulica","gospodarstwo","plac","sąsiad","most","miasto","wioska","poczta","tereny wiejskie","kościół","biblioteka","muzeum","bank"},
                                         {"garden","road","park","field","capital","street","farm","square","neighbour","bridge","city","village","post office","countryside","church","library","museum","bank"},
                                         {"el jardín","el camino","el parque","el campo","la capital","la calle","la granja","la plaza","el vecino","el puente","la ciudad","el pueblo","la oficina de correos","el campo","la iglesia","la biblioteca","el museo","el banco"}};
        private static string[,] school = {{"egzamin","ocena","znaczyć","ołówek","książka","szkoła","uczeń","słowo","uczyć","uczyć się","rozumieć","język","matematyka","zdać","nie zdać","historia","geografia","przerwa","pisać","tablica","klasa","długopis","praca domowa","zeszyt","nauczyciel","uniwersytet","ćwiczenie"},
                                           {"exam","mark","mean","pencil","book","school","student","word","teach","learn","understand","language","maths","pass","fail","history","geography","break","write","blackboard","class","pen","homework","copybook","teacher","university","exercise"},
                                           {"el examen","la nota","significar","el lápiz","el libro","la escuela","el alumno","la palabra","enseñar","aprender","entender","el idioma","las matemáticas","aprobar","suspender","la historia","la geografía","el descanso","escribir","la pizarra","la clase","el bolígrafo","los deberes","el cuaderno","el profesor","la universidad","el ejercicio"}};
        private static string[,] feature = {{"przystojny","stary","młody","ładny","elegancki","wysoki","niski","czysty","prosty","kręcony","brudny","piękny","brzydki","gruby","szczupły"},
                                            {"handsome","old","young","pretty","elegant","tall","short","clean","straight","curly","dirty","beautiful","ugly","fat","slim"},
                                            {"guapo","viejo","joven","bonito","elegante","alto","bajo","limpio","liso","rizado","sucio","hermoso","feo","gordo","delgado"}};
        private static string[,] nature = {{"przyroda","niebo","chmura","słońce","księżyc","jezioro","rzeka","morze","drzewo","liść","kwiat","roślina","trawa","las","góra","gorąco","ciepło","zimno","wiatr","pogoda","deszcz","śnieg","burza"},
                                           {"nature","sky","cloud","sun","moon","lake","river","sea","tree","leaf","flower","plant","grass","forest","mountain","hot","warm","cold","wind","weather","rain","snow","storm"},
                                           {"la naturaleza","el cielo","la nube","el sol","la luna","el lago","el río","el mar","el árbol","la hoja","la flor","la planta","la hierba","el bosque","la montaña","caliente","cálido","frío","el viento","el tiempo","la lluvia","la nieve","la tormenta"}};
        private static string[,] body = {{"głowa","włosy","ucho","oko","nos","ząb","usta","twarz","szyja","ramię","brzuch","plecy","ręka","noga","kolano","stopa","palec u nogi","palec u ręki","broda"},
                                         {"head","hair","ear","eye","nose","tooth","lips","face","neck","arm","stomach","back","hand","leg","knee","foot","toe","finger","beard" },
                                         {"la cabeza","el pelo","la oreja","el ojo","la nariz","el diente","los labios","la cara","el cuello","el brazo","el estómago","la espalda","la mano","la pierna","la rodilla","el pie","el dedo del pie","el dedo","la barba"}};
        private static string[,] clothes = {{"kurtka","skarpetka","pasek","okulary","szalik","rękawiczka","but","spodnie","parasol","koszulka","sukienka","czapka","kapelusz","spódnica","koszula","płaszcz","przymierzać","rozmiar"},
                                            {"jacket","sock","belt","glasses","scarf","glove","shoe","trousers","umbrella","T-shirt","dress","cap","hat","skirt","shirt","coat","try on","size"},
                                            {"la chaqueta","el calcetín","el cinturón","las gafas","la bufanda","el guante","el zapato","los pantalones","el paraguas","la camiseta","el vestido","la gorra","el sombrero","la falda","la camisa","el abrigo","probarse","la talla"}};
        private static string[,] countries = {{"Wielka Brytania (Zjednoczone Królestwo)","Japończyk, japoński","Japonia","Rosjanin, rosyjski","Rosja","Kanadyjczyk, kanadyjski","Kanada","Amerykanin, amerykański","Stany Zjednoczone Ameryki","Australijczyk, australijski","Australia","Grek, grecki","narodowość","kraj"},
                                              {"United Kingdom","Japanese","Japan","Russian","Russia","Canadian","Canada","American","United States of America","Australian","Australia","Greek","nationality","country"},
                                              {"el Reino Unido","japonés","Japón","ruso","Rusia","canadiense","Canadá","estadounidense","los Estados Unidos de América","australiano","Australia","griego","la nacionalidad","el país"}};
        private static string[,] toilet = {{"spóźniać się","ścielić łóżko","czesać się","ścierać kurz","myć","budzić się","spać","śpieszyć się"},
                                           {"be late","make the bed","comb","dust","wash","wake up","sleep","hurry"},
                                           {"llegar tarde","hacer la cama","peinarse","quitar el polvo","lavar","despertarse","dormir","darse prisa"}};
        private static string[,] relax = {{"relaksować się","śpiewać","pływać","przyjęcie, impreza","bawić się","zainteresowania","robić zdjęcia","wakacje","malować","słuchać","czytać","kino","teatr","koncert","oglądać","uprawiać sporty","biegać","tańczyć"},
                                          {"relax","sing","swim","party","play","hobbies","take photos","holiday","paint","listen","read","cinema","theatre","concert","watch","do sports","run","dance"},
                                          {"relajarse","cantar","nadar","la fiesta","jugar","los intereses","hacer fotos","las vacaciones","pintar","escuchar","leer","el cine","el teatro","el concierto","ver","hacer deporte","correr","bailar"}};
        private static string[,] feelings = {{"zmęczony","bać się","płakać","śmiać się","uśmiechać się","zdenerwowany","senny","zły (na kogoś)","smutny","szczęśliwy","nienawidzić","kochać","lubić","dumny","nudny","zaskakiwać","uczucie","myśleć","martwić się"},
                                             {"tired","be scared","cry","laugh","smile","nervous","sleepy","angry","sad","happy","hate","love","like","proud","boring","surprise","feeling","think","worry"},
                                             {"cansado","tener miedo","llorar","reír","sonreír","nervioso","tener sueño","enfadado","triste","feliz","odiar","amar","gustar","orgulloso","aburrido","sorprender","el sentimiento","pensar","preocuparse"}};
        private static string[,] shopping = {{"portfel","centrum handlowe","księgarnia","piekarnia","drogi","tani","płacić","bankomat","sklep","sprzedawać","pieniądze","targ","cena","koszyk","półka","reszta","kupować","zakupy","zamawiać","rachunek","kelner","menu","napiwek","stolik (rezerwacja)","rezerwacja","danie","przystawka","danie główne","konto bankowe","przelew","oszczędzać","pożyczać","rachunek (do zapłacenia)","gotówka","karta kredytowa","karta debetowa","oprocentowanie","kredyt","zadłużenie","wydawać (pieniądze)","budżet","waluta"},
                                             {"wallet","shopping center","bookshop","bakery","expensive","cheap","pay","cashpoint","shop","sell","money","market","price","basket","shelf","change","buy","shopping","order","bill","waiter","menu","tip","table (reservation)","reservation","dish","starter","main course","bank account","transfer","save (money)","borrow","bill (to pay)","cash","credit card","debit card","interest rate","loan","debt","spend (money)","budget","currency"},
                                             {"la cartera","el centro comercial","la librería","la panadería","caro","barato","pagar","el cajero automático","la tienda","vender","el dinero","el mercado","el precio","la cesta","la estantería","el cambio","comprar","las compras","pedir","la cuenta","el camarero","el menú","la propina","la mesa (reserva)","la reserva","el plato","el entrante","el plato principal","la cuenta bancaria","la transferencia","ahorrar","pedir prestado","la factura","el efectivo","la tarjeta de crédito","la tarjeta de débito","el tipo de interés","el préstamo","la deuda","gastar","el presupuesto","la moneda"} };
        private static string[,] job = {{"muzyk","malarz","naukowiec","policjant","strażak","pielęgniarka","architekt","sekretarka","mechanik","informatyk","programista","inżynier","aktor","artysta","lekarz","dziennikarz","sprzedawca","fryzjer","prawnik","dzwonić","kopiować","ekran","plik, dokument","klawiatura","telefon komórkowy","drukować","zapisywać","włączać","wyłączać","praca","biuro","komputer","szef","internet","hasło","konto","aplikacja","wiadomość","e-mail","link","ładować (telefon)","wifi","strona internetowa","przeglądarka","klikać","logować się","wylogowywać się","pobierać","wysyłać","media społecznościowe","aktualizować"},
                                        {"musician","painter","scientist","police officer","fireman","nurse","architect","secretary","mechanic","IT specialist","computer programmer","engineer","actor","artist","doctor","journalist","shop assistant","hairdresser","lawyer","phone","copy","screen","file","keyboard","mobile phone","print","save","turn on","turn off","work","office","computer","boss","internet","password","account","app","message","email","link","charge (phone)","wifi","website","browser","click","log in","log out","download","send","social media","update"},
                                        {"el músico","el pintor","el científico","el policía","el bombero","la enfermera","el arquitecto","la secretaria","el mecánico","el informático","el programador","el ingeniero","el actor","el artista","el médico","el periodista","el vendedor","el peluquero","el abogado","llamar","copiar","la pantalla","el archivo","el teclado","el móvil","imprimir","guardar","encender","apagar","el trabajo","la oficina","el ordenador","el jefe","el internet","la contraseña","la cuenta","la aplicación","el mensaje","el correo electrónico","el enlace","cargar (el teléfono)","el wifi","el sitio web","el navegador","hacer clic","iniciar sesión","cerrar sesión","descargar","enviar","las redes sociales","actualizar"}};
        private static string[,] character = {{"arogancki","radosny","nieśmiały","szalony","uparty","inteligentny","spokojny","towarzyski","odważny","miły","sympatyczny","uczciwy","mądry","cierpliwy","samolubny"},
                                              {"rude","cheerful","shy","crazy","stubborn","intelligent","calm","outgoing","brave","nice","friendly","honest","clever","patient","selfish" },
                                              {"arrogante","alegre","tímido","loco","testarudo","inteligente","tranquilo","sociable","valiente","amable","simpático","honesto","listo","paciente","egoísta"}};
        private static string[,] health = {{"pigułka, tabletka","choroba","chory","zdrowy","lekarstwo","karetka","apteka","łamać","kaszel","przeziębić się","grypa","gorączka","umawiać się (na wizytę)","ból","boleć","ból głowy","ból gardła","czuć się","szpital"},
                                           {"pill","illness","sick","healthy","medicine","ambulance","pharmacy","break","cough","catch a cold","flu","fever","make an appointment","pain","hurt","headache","sore throat","feel","hospital" },
                                           {"la pastilla","la enfermedad","enfermo","sano","el medicamento","la ambulancia","la farmacia","romper","la tos","resfriarse","la gripe","la fiebre","pedir cita","el dolor","doler","el dolor de cabeza","el dolor de garganta","sentirse","el hospital"}};
        private static string[,] celebrations = {{"Boże Narodzenie","Wielkanoc","urodziny","prezent","świętować","życzenia","choinka","fajerwerki","Nowy Rok","imieniny","gratulacje","zapraszać","gość","tort urodzinowy"},
                                                 {"Christmas","Easter","birthday","present","celebrate","wishes","Christmas tree","fireworks","New Year","name day","congratulations","invite","guest","birthday cake"},
                                                 {"la Navidad","la Pascua","el cumpleaños","el regalo","celebrar","los deseos","el árbol de Navidad","los fuegos artificiales","el Año Nuevo","el santo","las felicidades","invitar","el invitado","la tarta de cumpleaños"} };
        private static string[][,] kategorie = { numbers, colors, animals, time, family, home, tournee, food, speak, city, school, feature, nature, body, clothes, countries, toilet,
            relax, feelings, shopping, job, character, health, celebrations };
    }
}