namespace Dziekanowka.Mechanizm.JezykiObce
{
    public class Fiszki
    {
        public static string[,] numbers = {{"zero","jeden","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć","dziesięć","jedenaście","dwanaście","trzynaście","czternaście","piętnaście","szesnaście","siedemnaście","osiemnaście","dziewiętnaście","dwadzieścia","trzydzieści","czterdzieści","pięćdziesiąt","sześćdziesiąt","siedemdziesiąt","osiemdziesiąt","dziewięćdziesiąt","sto","tysiąc","milion","pierwszy","drugi","trzeci","czwarty","piąty","ostatni"},
                                    {"zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety","hundred","thousand","million","first","second","third","fourth","fifth","last"},
                                    {"cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve","diez","once","doce","trece","catorce","quince","dieciséis","diecisiete","dieciocho","diecinueve","veinte","treinta","cuarenta","cincuenta","sesenta","setenta","ochenta","noventa","cien","mil","millón","primero","segundo","tercero","cuarto","quinto","último"},
                                    {"nulla","unus","duo","tres","quattuor","quinque","sex","septem","octo","novem","decem","undecim","duodecim","tredecim","quattuordecim","quindecim","sedecim","septendecim","duodeviginti","undeviginti","viginti","triginta","quadraginta","quinquaginta","sexaginta","septuaginta","octoginta","nonaginta","centum","mille","decies centena milia","primus","secundus","tertius","quartus","quintus","ultimus"} };
        public static string[,] wordsMath = {{"numer","liczba","połowa","ćwiartka","całość","więcej","mniej","tyle_samo","kilka","wiele","mało","liczyć","obliczać","podwoić","parzysty","nieparzysty","suma","różnica","iloczyn","iloraz","cyfra","dodawać","odejmować","mnożyć","dzielić","równać się","procent","wynik","ułamek"},
                                      {"number","number","half","quarter","whole","more","less","the same amount","a few","a lot","little","count","calculate","double","even","odd","sum","difference","product","quotient","digit","add","subtract","multiply","divide","equal","percent","result","fraction"},
                                      {"el número","el número","la mitad","el cuarto","el todo","más","menos","la misma cantidad","unos pocos","mucho","poco","contar","calcular","duplicar","par","impar","la suma","la diferencia","el producto","el cociente","la cifra","sumar","restar","multiplicar","dividir","ser igual a","el porcentaje","el resultado","la fracción"},
                                      {"numerus","numerus","dimidium","quadrans","totum","plus","minus","tantundem","aliquot","multum","paucum","numerare","computare","duplicare","par","impar","summa","differentia","productus","-","digitus","addere","subtrahere","multiplicare","dividere","aequare","-","eventus","-"} };
        public static string[,] colors = {{"czarny","biały","czerwony","żółty","zielony","niebieski","szary","różowy","pomarańczowy","brązowy","fioletowy","złoty","srebrny","kolor"},
                                    {"black","white","red","yellow","green","blue","grey","pink","orange","brown","purple","gold","silver","colour"},
                                    {"negro","blanco","rojo","amarillo","verde","azul","gris","rosa","naranja","marrón","morado","dorado","plateado","el color"},
                                    {"niger","albus","ruber","flavus","viridis","caeruleus","canus","roseus","-","fulvus","purpureus","aureus","argenteus","color"} };
        public static string[,] animalsHome = {{"kot","pies","ryba","chomik","papuga","krowa","koń","kaczka","osioł","kura","świnia","owca","kogut","indyk","koza","gęś","ptak","ślimak","motyl","mucha","mysz","pszczoła","królik","komar"},
                                         {"cat","dog","fish","hamster","parrot","cow","horse","duck","donkey","hen","pig","sheep","rooster","turkey","goat","goose","bird","snail","butterfly","fly","mouse","bee","rabbit","mosquito"},
                                         {"el gato","el perro","el pez","el hámster","el loro","la vaca","el caballo","el pato","el burro","la gallina","el cerdo","la oveja","el gallo","el pavo","la cabra","el ganso","el pájaro","el caracol","la mariposa","la mosca","el ratón","la abeja","el conejo","el mosquito"},
                                         {"felis","canis","piscis","-","psittacus","bos","equus","anas","asinus","gallina","porcus","ovis","gallus","-","capra","anser","avis","cochlea","papilio","musca","mus","apis","cuniculus","culex"} };
        public static string[,] animalsWild = {{"lew","słoń","wilk","lis","żaba","tygrys","niedźwiedź","wąż","żyrafa","zebra","kangur","delfin","wieloryb","rekin","orzeł","sowa","jeleń","sarna","hipopotam","nosorożec","żółw","jeż"},
                                         {"lion","elephant","wolf","fox","frog","tiger","bear","snake","giraffe","zebra","kangaroo","dolphin","whale","shark","eagle","owl","deer","roe deer","hippopotamus","rhinoceros","turtle","hedgehog"},
                                         {"el león","el elefante","el lobo","el zorro","la rana","el tigre","el oso","la serpiente","la jirafa","la cebra","el canguro","el delfín","la ballena","el tiburón","el águila","el búho","el ciervo","el corzo","el hipopótamo","el rinoceronte","la tortuga","el erizo"},
                                         {"leo","elephantus","lupus","vulpes","rana","tigris","ursus","serpens","-","-","-","delphinus","balaena","-","aquila","-","cervus","-","hippopotamus","rhinoceros","testudo","ericius"} };
        public static string[,] animalWords = {{"zwierzę","zwierzak_domowy","szczekać","miauczeć","głaskać","dziki","oswojony","futro","sierść","pióra","łapa","ogon","skrzydło","rżeć","muczeć","beczeć","kwakać","ryczeć","róg","kieł","pazur","grzywa","polować","wysiadywać jaja","znosić jaja","stado","gniazdo","nora"},
                                        {"animal","pet","bark","meow","stroke/pet","wild","tame","fur","coat (animal hair)","feathers","paw","tail","wing","neigh","moo","bleat","quack","roar","horn","fang/tusk","claw","mane","hunt","hatch/incubate","lay eggs","herd/flock","nest","burrow/den"},
                                        {"el animal","la mascota","ladrar","maullar","acariciar","salvaje","domesticado","el pelaje","el pelo","las plumas","la pata","la cola","el ala","relinchar","mugir","balar","graznar","rugir","el cuerno","el colmillo","la garra","la melena","cazar","incubar","poner huevos","la manada","el nido","la madriguera"},
                                        {"animal","-","latrare","-","-","ferus","domesticus","pellis","-","pluma","-","cauda","ala","hinnire","mugire","balare","-","rugire","cornu","dens","unguis","iuba","venari","-","-","grex","nidus","-"} };
        public static string[,] kitchen = {{"lodówka","zlew","kuchnia","garnek","patelnia","piekarnik","kuchenka (płyta)","mikrofalówka","zmywarka","czajnik","deska do krojenia","zmywać naczynia","kroić","smażyć","gotować się (wrzeć)","gotować","mieszać","obierać","piec","dodawać","ważyć","siekać","podgrzewać","jeść","pić","nakrywać do stołu","sprzątać ze stołu","smakować","talerz","widelec","nóż","łyżka","łyżeczka","szklanka","kubek","filiżanka","serwetka","obrus","śniadanie","obiad","kolacja","przekąska","posiłek","przepis","składnik"},
                                            {"fridge","sink","kitchen","pot","pan","oven","stove/hob","microwave","dishwasher","kettle","cutting board","wash the dishes","cut","fry","boil","cook","mix","peel","bake","add","weigh","chop","heat up","eat","drink","set the table","clear the table","taste","plate","fork","knife","spoon","teaspoon","glass","mug","cup","napkin","tablecloth","breakfast","lunch/dinner","supper/dinner","snack/starter","meal","recipe","ingredient"},
                                            {"la nevera","el fregadero","la cocina","la olla","la sartén","el horno","la placa de cocina","el microondas","el lavavajillas","el hervidor","la tabla de cortar","fregar los platos","cortar","freír","hervir","cocinar","mezclar","pelar","hornear","añadir","pesar","picar","calentar","comer","beber","poner la mesa","recoger la mesa","probar","el plato","el tenedor","el cuchillo","la cuchara","la cucharilla","el vaso","la taza","la taza","la servilleta","el mantel","el desayuno","el almuerzo","la cena","el aperitivo","la comida","la receta","el ingrediente"},
                                            {"-","-","culina","olla","-","furnus","-","-","-","-","-","vasa lavare","secare","frigere","fervere","-","miscere","-","coquere","addere","ponderare","concidere","calefacere","edere","bibere","-","-","gustare","catinus","furca","culter","cochlear","-","poculum","-","-","mappa","mantele","ientaculum","prandium","cena","gustatio","cibus","-","-"} };
        public static string[,] bathroom = {{"prysznic","wanna","lustro","łazienka","czesać się","myć","pralka","wieszać pranie","toaleta","umywalka","ręcznik","mydło","szampon","pasta do zębów","szczoteczka do zębów","myć zęby","kąpać się","golić się","suszarka do włosów","papier toaletowy","szczotka do włosów","golarka"},
                                          {"shower","bathtub","mirror","bathroom","comb","wash","washing machine","hang out the laundry","toilet","sink (bathroom)","towel","soap","shampoo","toothpaste","toothbrush","brush teeth","bathe","shave","hair dryer","toilet paper","hairbrush","razor"},
                                          {"la ducha","la bañera","el espejo","el baño","peinarse","lavar","la lavadora","tender la ropa","el aseo","el lavabo","la toalla","el jabón","el champú","la pasta de dientes","el cepillo de dientes","cepillarse los dientes","bañarse","afeitarse","el secador de pelo","el papel higiénico","el cepillo del pelo","la maquinilla de afeitar"},
                                          {"-","alveus","speculum","balneum","se pectere","lavare","-","-","latrina","-","linteum","sapo","-","-","-","dentes fricare","lavari","se radere","-","-","-","novacula"} };
        public static string[,] livingBedroom = {{"szafa","książka","regał","stół","krzesło","telewizor","fotel","łóżko","kanapa","dywan","salon","sypialnia","zasłony","ścielić łóżko","ścierać kurz","budzić się","spać","sprzątać","odkurzać","prasować","zamiatać","lampa","poduszka","kołdra","pościel","budzik"},
                                           {"wardrobe","book","bookshelf","table","chair","TV","armchair","bed","sofa","carpet","living room","bedroom","curtains","make the bed","dust","wake up","sleep","clean/tidy up","vacuum","iron","sweep","lamp","pillow","duvet","bedding","alarm clock"},
                                           {"el armario","el libro","la estantería","la mesa","la silla","el televisor","el sillón","la cama","el sofá","la alfombra","el salón","el dormitorio","las cortinas","hacer la cama","quitar el polvo","despertarse","dormir","limpiar","pasar la aspiradora","planchar","barrer","la lámpara","la almohada","el edredón","la ropa de cama","el despertador"},
                                           {"armarium","liber","pluteus","mensa","sella","-","-","lectus","-","tapete","-","cubiculum","vela","-","-","expergisci","dormire","-","-","-","verrere","lucerna","pulvinus","-","-","-"} };
        public static string[,] buildingGeneral = {{"klucz","pokój","okno","ściana","podłoga","parter","drzwi","sufit","garaż","piwnica","adres","dom","mieszkanie","mieszkać","piętro","balkon","taras","schody","winda","strych","żarówka","grzejnik","wynosić śmieci","skrzynka pocztowa","dzwonek","remontować","ogród"},
                                            {"key","room","window","wall","floor","ground floor","door","ceiling","garage","cellar","address","house","flat","live","storey","balcony","terrace","stairs","lift","attic","lightbulb","radiator","take out the rubbish","mailbox","doorbell","renovate","garden"},
                                            {"la llave","la habitación","la ventana","la pared","el suelo","la planta baja","la puerta","el techo","el garaje","el sótano","la dirección","la casa","el piso","vivir","la planta","el balcón","la terraza","las escaleras","el ascensor","el desván","la bombilla","el radiador","sacar la basura","el buzón","el timbre","reformar","el jardín"},
                                            {"clavis","conclave","fenestra","paries","solum","-","ianua","lacunar","-","cella","-","domus","-","habitare","-","-","solarium","scalae","-","-","-","-","-","-","-","renovare","hortus"} };
        public static string[,] vegetables = {{"groch","jarmuż","pasternak","pietruszka","burak","brukselka","sałata","marchew","ziemniak","cebula","szczypiorek","pomidor","papryka","ogórek","czosnek","rzodkiewka","szpinak","rukola","batat","szczaw","seler","boćwina","por","fasola","bób","ciecierzyca","bakłażan","cukinia","dynia","brokuł","kalafior","kapusta włoska","kapusta pekińska","szparagi","seler naciowy","soczewica"},
                                       {"pea","kale","parsnip","parsley","beetroot","Brussels sprout","lettuce","carrot","potato","onion","chives","tomato","pepper","cucumber","garlic","radish","spinach","rocket/arugula","sweet potato","sorrel","celery","chard","leek","beans","broad bean","chickpea","eggplant","courgette/zucchini","pumpkin","broccoli","cauliflower","Savoy cabbage","Chinese cabbage","asparagus","celery (stalk)","lentil"},
                                       {"el guisante","la berza","la chirivía","el perejil","la remolacha","la col de Bruselas","la lechuga","la zanahoria","la patata","la cebolla","el cebollino","el tomate","el pimiento","el pepino","el ajo","el rábano","la espinaca","la rúcula","el boniato","la acedera","el apio","la acelga","el puerro","las judías","las habas","el garbanzo","la berenjena","el calabacín","la calabaza","el brócoli","la coliflor","la col de Milán","la col china","los espárragos","el apio","la lenteja"},
                                       {"pisum","-","pastinaca","petroselinum","beta","-","lactuca","carota","-","cepa","-","-","-","cucumis","allium","raphanus","-","eruca","-","rumex","apium","-","porrum","phaseolus","faba","cicer","-","-","cucurbita","-","-","-","-","asparagus","apium","lens"} };
		public static string[,] fruits = {{"brzoskwinia","nektarynka","morela","śliwka","wiśnia","czereśnia","jabłko","gruszka","truskawka","malina","jeżyna","borówka","porzeczka czerwona","porzeczka czarna","żurawina","pomarańcza","mandarynka","cytryna","grejpfrut","banan","ananas","mango","papaja","marakuja","kokos","awokado","arbuz","melon","winogrono jasne","winogrono różowe","winogrono ciemne","kiwi","figa","granat","agrest","daktyl"},
                                    {"peach","nectarine","apricot","plum","sour cherry","sweet cherry","apple","pear","strawberry","raspberry","blackberry","blueberry","redcurrant","blackcurrant","cranberry","orange","tangerine/mandarin","lemon","grapefruit","banana","pineapple","mango","papaya","passion fruit","coconut","avocado","watermelon","melon","light grapes","pink grapes","dark grapes","kiwi","fig","pomegranate","gooseberry","date"},
                                    {"el melocotón","la nectarina","el albaricoque","la ciruela","la guinda","la cereza","la manzana","la pera","la fresa","la frambuesa","la mora","el arándano","la grosella roja","la grosella negra","el arándano rojo","la naranja","la mandarina","el limón","el pomelo","el plátano","la piña","el mango","la papaya","la maracuyá","el coco","el aguacate","la sandía","el melón","la uva blanca","la uva rosada","la uva negra","el kiwi","el higo","la granada","la grosella espinosa","el dátil"},
                                    {"malum persicum","-","malum armeniacum","prunum","cerasum","cerasum","malum","pirum","fragum","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","melopepo","uva","uva","uva","-","ficus","malum punicum","-","dactylus"} };
        public static string[,] farmCrops = {{"żyto","jęczmień","pszenica","ryż","owies","gryka","orkisz","koniczyna","rzepa pastewna","sorgo","kukurydza","proso","rzepak","słonecznik","chmiel","konopia","mak","soja","trzcina cukrowa","komosa ryżowa"},
                                              {"rye","barley","wheat","rice","oats","buckwheat","spelt","clover","fodder turnip","sorghum","corn/maize","millet","rapeseed","sunflower","hops","hemp","poppy","soybean","sugar cane","quinoa"},
                                              {"el centeno","la cebada","el trigo","el arroz","la avena","el trigo sarraceno","la escanda","el trébol","el nabo forrajero","el sorgo","el maíz","el mijo","la colza","el girasol","el lúpulo","el cáñamo","la amapola","la soja","la caña de azúcar","la quinoa"},
                                              {"secale","hordeum","triticum","oryza","avena","-","far","trifolium","napus","-","-","panicum","-","-","-","cannabis","papaver","-","-","-"} };
        public static string[,] soups = {{"rosół","barszcz czerwony","żurek","krupnik","zupa pomidorowa","zupa ogórkowa","zupa grzybowa","kapuśniak","grochówka","zupa fasolowa","zupa cebulowa","chłodnik","krem z brokułów","krem z dyni","krem z kalafiora","zupa jarzynowa","zupa mleczna","flaki","zupa szczawiowa","zupa rybna"},
                                   {"chicken/meat broth","beetroot soup","sour rye soup","barley soup","tomato soup","cucumber soup","mushroom soup","cabbage soup","pea soup","bean soup","onion soup","cold beetroot soup","broccoli cream soup","pumpkin cream soup","cauliflower cream soup","vegetable soup","milk soup","tripe soup","sorrel soup","fish soup"},
                                   {"el caldo de pollo","la sopa de remolacha","el żurek","la sopa de cebada","la sopa de tomate","la sopa de pepino","la sopa de champiñones","la sopa de col","la sopa de guisantes","la sopa de judías","la sopa de cebolla","la sopa fría de remolacha","la crema de brócoli","la crema de calabaza","la crema de coliflor","la sopa de verduras","la sopa de leche","los callos","la sopa de acedera","la sopa de pescado"},
                                   {"ius","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"} };
        public static string[,] mainDishes = {{"kotlet schabowy","kotlet mielony","stek","bitki","gołąbki","karkówka","gulasz","pieczeń wołowa","indyk duszony","ratatouille","leczo","fasolka po bretońsku","bigos","placek po węgiersku","risotto","lasagne"},
                                        {"breaded pork cutlet","meat patty/burger","steak","beef roulade","cabbage rolls","pork neck","goulash","roast beef","stewed turkey","ratatouille","lecho","Breton-style beans","bigos (hunter's stew)","Hungarian-style pancake","risotto","lasagne"},
                                        {"la chuleta empanada","la hamburguesa","el filete","los rollitos de carne","los rollitos de col","el cuello de cerdo","el gulash","el rosbif","el pavo estofado","el ratatouille","el lecho","las judías a la bretona","el bigos","la tortita húngara","el risotto","la lasaña"},
                                        {"-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"} };
        public static string[,] otherDishes = {{"jajecznica","jajko sadzone","omlet","shakshuka","naleśniki","racuchy","pierogi ruskie","pierogi z mięsem","pierogi z kapustą i grzybami","pierogi z owocami","knedle","pizza","placki ziemniaczane","frytki","kanapka","hot dog","hamburger","tosty"},
                                        {"scrambled eggs","fried egg","omelette","shakshuka","pancakes","fritters","potato and cheese dumplings","meat dumplings","cabbage and mushroom dumplings","fruit dumplings","dumplings (bread/potato)","pizza","potato pancakes","chips/fries","sandwich","hot dog","hamburger","toast"},
                                        {"los huevos revueltos","el huevo frito","la tortilla francesa","la shakshuka","los crepes","los buñuelos","los pierogi rusos","los pierogi de carne","los pierogi de col y setas","los pierogi de frutas","las albóndigas de pan","la pizza","las tortitas de patata","las patatas fritas","el sándwich","el perrito caliente","la hamburguesa","la tostada"},
                                        {"-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"} };
        public static string[,] pantry = {{"śmietana","masło","ser","twaróg","jajko","miód","smalec","mięso mielone","wędlina","kiełbasa","salami","pasztet","mąka","makaron","płatki","chleb","bułka","ogórek kiszony","kapusta kiszona","burak kiszony","dżem","ketchup"},
                                    {"cream","butter","cheese","cottage cheese","egg","honey","lard","minced meat","cold cuts","sausage","salami","pâté","flour","pasta","flakes","bread","bread roll","pickled cucumber","sauerkraut","pickled beetroot","jam","ketchup"},
                                    {"la nata","la mantequilla","el queso","el requesón","el huevo","la miel","la manteca","la carne picada","los fiambres","la salchicha","el salami","el paté","la harina","la pasta","los copos","el pan","el panecillo","el pepinillo en vinagre","el chucrut","la remolacha encurtida","la mermelada","el kétchup"},
                                    {"-","butyrum","caseus","-","ovum","mel","laridum","-","-","botulus","-","-","farina","-","-","panis","-","-","-","-","-","-"} };
        public static string[,] drinks = {{"mleko","kompot","wino","sok","kawa","woda","herbata","piwo","napój gazowany","koktajl","kakao","napój"},
                                    {"milk","fruit compote","wine","juice","coffee","water","tea","beer","fizzy drink/soda","cocktail/smoothie","hot chocolate/cocoa","drink (general)"},
                                    {"la leche","el compota","el vino","el zumo","el café","el agua","el té","la cerveza","el refresco","el cóctel","el cacao","la bebida"},
                                    {"lac","-","vinum","sucus","-","aqua","-","cervisia","-","-","-","potio"} };
        public static string[,] spices = {{"oliwki","olej","sól","czarny pieprz","majeranek","oregano","bazylia","proszek do pieczenia","cynamon","tymianek","rozmaryn","liście laurowe","ziele angielskie","chili","kurkuma","gałka muszkatołowa","wanilia","cukier","ocet","musztarda","drożdże","curry"},
                                   {"olives","oil","salt","black pepper","marjoram","oregano","basil","baking powder","cinnamon","thyme","rosemary","bay leaves","allspice","chili","turmeric","nutmeg","vanilla","sugar","vinegar","mustard","yeast","curry"},
                                   {"las aceitunas","el aceite","la sal","la pimienta negra","la mejorana","el orégano","la albahaca","la levadura química","la canela","el tomillo","el romero","las hojas de laurel","la pimienta de Jamaica","el chile","la cúrcuma","la nuez moscada","la vainilla","el azúcar","el vinagre","la mostaza","la levadura","el curry"},
                                   {"oliva","oleum","sal","piper","-","origanum","ocimum","-","cinnamomum","thymus","ros marinus","laurus","-","-","-","-","-","-","acetum","sinapi","fermentum","-"} };
        public static string[,] bakedSweets = {{"sernik","babka piaskowa","ciasto owocowe","drożdżówka","czekolada","cukierki","lody","pączek","piernik","tort","guma do żucia","makowiec","budyń","galaretka","ciastko","lizak"},
                                         {"cheesecake","sand cake/pound cake","fruit cake","sweet yeast bun","chocolate","sweets/candy","ice cream","donut","gingerbread","celebration cake","chewing gum","poppy seed cake","pudding","jelly","cookie/biscuit","lollipop"},
                                         {"la tarta de queso","el bizcocho","el pastel de frutas","el bollo dulce","el chocolate","los caramelos","el helado","el donut","el pan de jengibre","la tarta","el chicle","el pastel de amapola","el pudín","la gelatina","la galleta","el chupachús"},
                                         {"placenta","-","-","-","-","dulcia","-","-","-","-","-","-","-","-","crustulum","-"} };
        public static string[,] fish = {{"łosoś","pstrąg","halibut","okoń","śledź","dorsz","karp","tuńczyk","szczupak","sum","makrela","flądra","sardynka","krewetka","ośmiornica"},
                                  {"salmon","trout","halibut","perch","herring","cod","carp","tuna","pike","catfish","mackerel","flounder","sardine","shrimp/prawn","octopus"},
                                  {"el salmón","la trucha","el halibut","la perca","el arenque","el bacalao","la carpa","el atún","el lucio","el siluro","la caballa","el lenguado","la sardina","la gamba","el pulpo"},
                                  {"salmo","trutta","-","perca","-","-","carpio","thynnus","lucius","silurus","scomber","-","-","-","polypus"} };
        public static string[,] mushrooms = {{"pieczarka","rydz","podgrzybek","borowik","kurka","maślak","koźlarz","gąska","muchomor","kania","grzyb","zbierać grzyby","jadalny","trujący"},
                                       {"button mushroom","saffron milk cap","boletus (brown cap)","porcini/cep","chanterelle","slippery jack","leccinum","tricholoma","fly agaric","parasol mushroom","mushroom","to pick mushrooms","edible","poisonous"},
                                       {"el champiñón","el níscalo","el boleto","el boleto comestible","el rebozuelo","el boleto anillado","el leccinum","la seta de San Jorge","la matamoscas","la matacandiles","la seta","recolectar setas","comestible","venenoso"},
                                       {"-","-","-","-","-","-","-","-","-","-","fungus","-","edibilis","venenosus"} };
        public static string[,] mealWordsDescriptions = {{"głodny","spragniony","smaczny","niesmaczny","świeży","nieświeży","słodki","słony","kwaśny","gorzki","pikantny"},
                                                   {"hungry","thirsty","tasty","tasteless","fresh","stale","sweet","salty","sour","bitter","spicy"},
                                                   {"hambriento","sediento","sabroso","insípido","fresco","pasado","dulce","salado","agrio","amargo","picante"},
                                                   {"esuriens","sitiens","sapidus","insipidus","recens","-","dulcis","salsus","acidus","amarus","-"} };
        public static string[,] familyCore = {{"rodzina","ojciec","matka","córka","syn","rodzic","mężczyzna","kobieta","mąż","żona","dziecko","brat","siostra","babcia","dziadek","wnuk","wnuczka","chłopiec","dziewczynka"},
                                        {"family","father","mother","daughter","son","parent","man","woman","husband","wife","child","brother","sister","grandmother","grandfather","grandson","granddaughter","boy","girl"},
                                        {"la familia","el padre","la madre","la hija","el hijo","el padre/la madre","el hombre","la mujer","el marido","la esposa","el niño","el hermano","la hermana","la abuela","el abuelo","el nieto","la nieta","el niño","la niña"},
                                        {"familia","pater","mater","filia","filius","parens","vir","femina","maritus","uxor","infans","frater","soror","avia","avus","nepos","neptis","puer","puella"} };
        public static string[,] familyExtended = {{"wujek","ciocia","kuzyn","teść","teściowa","zięć","synowa","szwagier","szwagierka","bratanek","bratanica","siostrzeniec","siostrzenica"},
                                            {"uncle","aunt","cousin","father-in-law","mother-in-law","son-in-law","daughter-in-law","brother-in-law","sister-in-law","nephew","niece","nephew","niece"},
                                            {"el tío","la tía","el primo","el suegro","la suegra","el yerno","la nuera","el cuñado","la cuñada","el sobrino","la sobrina","el sobrino","la sobrina"},
                                            {"avunculus","amita","consobrinus","socer","socrus","gener","nurus","levir","glos","-","-","-","-"} };
        public static string[,] familyStatus = {{"chłopak (sympatia)","dziewczyna (sympatia)","narzeczony","narzeczona","kawaler","panna","żonaty","mężatka","ślub","wdowa","przyjaciel","bliźniaki","sierota","dorosły"},
                                          {"boyfriend","girlfriend","fiancé","fiancée","bachelor","single woman/maiden","married","married","wedding","widow","friend","twins","orphan","adult"},
                                          {"el novio","la novia","el prometido","la prometida","el soltero","la soltera","casado","casada","la boda","la viuda","el amigo","los gemelos","el huérfano","el adulto"},
                                          {"-","-","sponsus","sponsa","caelebs","virgo","-","-","nuptiae","vidua","amicus","gemini","orbus","adultus"} };
        public static string[,] familyVerbs = {{"być razem","urodzić się","wychowywać","opiekować się","zaręczyć się","pobrać się","umrzeć","adoptować","odwiedzać (rodzinę)","przytulać","dorastać","rozpieszczać"},
                                         {"be together","be born","raise/bring up","take care of","get engaged","get married","die","adopt","visit (family)","hug","grow up","spoil/pamper"},
                                         {"estar juntos","nacer","criar","cuidar","prometerse","casarse","morir","adoptar","visitar","abrazar","crecer","mimar"},
                                         {"-","nasci","educare","curare","spondere","nubere","mori","adoptare","visere","amplecti","crescere","-"} };
        public static string[,] timeUnitsMeasure = {{"sekunda","minuta","kwadrans","godzina","dzień","tydzień","weekend","miesiąc","kwartał","rok","dekada","wiek"},
                                              {"second","minute","quarter (of an hour)","hour","day","week","weekend","month","quarter (of a year)","year","decade","century"},
                                              {"el segundo","el minuto","el cuarto de hora","la hora","el día","la semana","el fin de semana","el mes","el trimestre","el año","la década","el siglo"},
                                              {"-","minuta","-","hora","dies","hebdomas","-","mensis","-","annus","decas","saeculum"} };
        public static string[,] timeDayParts = {{"czas","noc","rano","popołudnie","wieczór","pora roku","świt","zmierzch","północ","południe","brzask","wschód słońca","zachód słońca"},
                                          {"time","night","morning","afternoon","evening","season","dawn","dusk/twilight","midnight","noon","daybreak","sunrise","sunset"},
                                          {"el tiempo","la noche","la mañana","la tarde","el atardecer","la estación","el amanecer","el crepúsculo","la medianoche","el mediodía","el alba","la salida del sol","la puesta de sol"},
                                          {"tempus","nox","mane","-","vesper","-","aurora","crepusculum","media nox","meridies","-","ortus solis","occasus solis"} };
        public static string[,] timeCalendar = {{"poniedziałek","wtorek","środa","czwartek","piątek","sobota","niedziela","styczeń","luty","marzec","kwiecień","maj","czerwiec","lipiec","sierpień","wrzesień","październik","listopad","grudzień","wiosna","lato","jesień","zima"},
                                          {"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday","January","February","March","April","May","June","July","August","September","October","November","December","spring","summer","autumn","winter"},
                                          {"el lunes","el martes","el miércoles","el jueves","el viernes","el sábado","el domingo","enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre","la primavera","el verano","el otoño","el invierno"},
                                          {"dies Lunae","dies Martis","dies Mercurii","dies Iovis","dies Veneris","dies Saturni","dies Solis","Ianuarius","Februarius","Martius","Aprilis","Maius","Iunius","Iulius","Augustus","September","October","November","December","ver","aestas","autumnus","hiems"} };
        public static string[,] timeAdverbs = {{"dzisiaj","wczoraj","jutro","codziennie","nigdy","zawsze","zwykle","czasami","rzadko","ostatnio","teraz","wkrótce","później","wcześniej","już","jeszcze nie","podczas","od (czasu)","do (czasu)","temu","przed (czasem)","po (czasie)","chwila","natychmiast","wreszcie/w końcu","na razie","na zawsze","wtedy"},
                                        {"today","yesterday","tomorrow","every day","never","always","usually","sometimes","rarely","recently","now","soon","later","earlier","already","not yet","during","since","until","ago","before (time)","after (time)","moment","immediately","finally/at last","for now","forever","then"},
                                        {"hoy","ayer","mañana","todos los días","nunca","siempre","normalmente","a veces","raramente","recientemente","ahora","pronto","más tarde","antes","ya","todavía no","durante","desde","hasta","hace","antes de","después de","el momento","inmediatamente","por fin","por ahora","para siempre","entonces"},
                                        {"hodie","heri","cras","cotidie","numquam","semper","plerumque","interdum","raro","nuper","nunc","mox","postea","antea","iam","nondum","-","-","-","abhinc","ante","post","momentum","statim","tandem","-","in aeternum","tum"} };
        public static string[,] body = {{"głowa","włosy","ucho","oko","nos","ząb","usta","twarz","szyja","ramię","brzuch","plecy","ręka","noga","kolano","stopa","palec u nogi","palec u ręki","broda","czoło","brew","rzęsy","policzek","podbródek","łokieć","nadgarstek","biodro","udo","łydka","kostka","klatka piersiowa","skóra","paznokieć","język","serce","kość","mózg","krew","pięta","czaszka"},
                                 {"head","hair","ear","eye","nose","tooth","lips","face","neck","arm","stomach","back","hand","leg","knee","foot","toe","finger","beard","forehead","eyebrow","eyelashes","cheek","chin","elbow","wrist","hip","thigh","calf","ankle","chest","skin","nail","tongue","heart","bone","brain","blood","heel","skull"},
                                 {"la cabeza","el pelo","la oreja","el ojo","la nariz","el diente","los labios","la cara","el cuello","el brazo","el estómago","la espalda","la mano","la pierna","la rodilla","el pie","el dedo del pie","el dedo","la barba","la frente","la ceja","las pestañas","la mejilla","la barbilla","el codo","la muñeca","la cadera","el muslo","la pantorrilla","el tobillo","el pecho","la piel","la uña","la lengua","el corazón","el hueso","el cerebro","la sangre","el talón","el cráneo"},
                                 {"caput","capillus","auris","oculus","nasus","dens","os","facies","collum","brachium","stomachus","tergum","manus","crus","genu","pes","digitus","digitus","barba","frons","supercilium","cilium","gena","mentum","cubitum","-","coxa","femur","-","talus","pectus","cutis","-","lingua","cor","os","cerebrum","cruor","calx","cranium"} };
        public static string[,] clothes = {{"kurtka","skarpetka","pasek","okulary","szalik","rękawiczka","but","spodnie","parasol","koszulka","sukienka","czapka","kapelusz","spódnica","koszula","płaszcz","przymierzać","rozmiar","krawat","bielizna","majtki","biustonosz","piżama","sweter","bluza","garnitur","rajstopy","klapki","sandały","strój","ubranie","nosić (ubranie)","ubierać się","rozbierać się","dres","strój kąpielowy","fartuch"},
                                    {"jacket","sock","belt","glasses","scarf","glove","shoe","trousers","umbrella","T-shirt","dress","cap","hat","skirt","shirt","coat","try on","size","tie","underwear","panties","bra","pyjamas","sweater","hoodie/sweatshirt","suit","tights","flip-flops","sandals","outfit","clothes/garment","to wear","to get dressed","to get undressed","tracksuit","swimsuit","apron"},
                                    {"la chaqueta","el calcetín","el cinturón","las gafas","la bufanda","el guante","el zapato","los pantalones","el paraguas","la camiseta","el vestido","la gorra","el sombrero","la falda","la camisa","el abrigo","probarse","la talla","la corbata","la ropa interior","las bragas","el sujetador","el pijama","el jersey","la sudadera","el traje","las medias","las chanclas","las sandalias","el conjunto","la ropa","llevar","vestirse","desvestirse","el chándal","el bañador","el delantal"},
                                    {"-","tibiale","cingulum","-","-","-","calceus","bracae","-","tunicula","stola","pilleus","petasus","-","tunica","paenula","-","-","-","subligaculum","-","-","-","-","-","-","-","solea","solea","-","vestimentum","gerere","-","-","-","-","-"} };
        public static string[,] materials = {{"drewno","metal","plastik","szkło","bawełna","wełna","skóra","jedwab","len","guma","papier","kamień","beton","cegła","stal","ceramika","piasek","żelazo","glina"},
                                       {"wood","metal","plastic","glass","cotton","wool","leather","silk","linen","rubber","paper","stone","concrete","brick","steel","ceramics","sand","iron","clay"},
                                       {"la madera","el metal","el plástico","el vidrio","el algodón","la lana","el cuero","la seda","el lino","la goma","el papel","la piedra","el hormigón","el ladrillo","el acero","la cerámica","la arena","el hierro","la arcilla"},
                                       {"lignum","metallum","-","vitrum","-","lana","corium","-","linum","-","-","lapis","-","-","-","-","arena","ferrum","argilla"} };
        public static string[,] school = {{"egzamin","ocena","ołówek","szkoła","uczeń","uczyć","uczyć się","rozumieć","język","matematyka","zdać","nie zdać","historia","geografia","przerwa","tablica","klasa","długopis","praca domowa","zeszyt","nauczyciel","uniwersytet","ćwiczenie","biologia","chemia","fizyka","plastyka","muzyka","wychowanie fizyczne","informatyka","religia","gumka (do mazania)","linijka","plecak","temperówka","kolega z klasy","liceum","podstawówka","wykład","student","stypendium","semestr","stołówka","sala gimnastyczna"},
                                    {"exam","mark","pencil","school","student","teach","learn","understand","language","maths","pass","fail","history","geography","break","blackboard/notebook","class","pen","homework","copybook","teacher","university","exercise","biology","chemistry","physics","art class","music","physical education","IT/computing","religion","eraser","ruler","backpack","pencil sharpener","classmate","secondary school","primary school","lecture","student (university)","scholarship","semester","canteen","gym/sports hall"},
                                    {"el examen","la nota","el lápiz","la escuela","el alumno","enseñar","aprender","entender","el idioma","las matemáticas","aprobar","suspender","la historia","la geografía","el descanso","la pizarra","la clase","el bolígrafo","los deberes","el cuaderno","el profesor","la universidad","el ejercicio","la biología","la química","la física","la plástica","la música","la educación física","la informática","la religión","la goma de borrar","la regla","la mochila","el sacapuntas","el compañero de clase","el instituto","la escuela primaria","la conferencia","el estudiante","la beca","el semestre","el comedor","el gimnasio"},
                                    {"examen","-","-","schola","discipulus","docere","discere","intellegere","lingua","mathematica","-","-","historia","geographia","-","tabula","classis","-","-","-","magister","universitas","exercitium","-","-","physica","-","musica","-","-","religio","-","regula","-","-","condiscipulus","Lyceum","-","praelectio","studiosus","-","-","-","palaestra"} };
        public static string[,] nature = {{"przyroda","niebo","chmura","słońce","księżyc","jezioro","rzeka","morze","drzewo","liść","kwiat","roślina","trawa","las","góra","wiatr","pogoda","deszcz","śnieg","burza","gwiazda","ocean","staw","wodospad","dolina","wyspa","pustynia","wzgórze","jaskinia","mgła","grad","tęcza","błyskawica","piorun","grzmot","korzeń","gałąź","pień","nasiono","planeta","wybrzeże","bagno"},
                                   {"nature","sky","cloud","sun","moon","lake","river","sea","tree","leaf","flower","plant","grass","forest","mountain","wind","weather","rain","snow","storm","star","ocean","pond","waterfall","valley","island","desert","hill","cave","fog","hail","rainbow","lightning (bolt)","thunderbolt","thunder","root","branch","trunk","seed","planet","coast","swamp"},
                                   {"la naturaleza","el cielo","la nube","el sol","la luna","el lago","el río","el mar","el árbol","la hoja","la flor","la planta","la hierba","el bosque","la montaña","el viento","el tiempo","la lluvia","la nieve","la tormenta","la estrella","el océano","el estanque","la cascada","el valle","la isla","el desierto","la colina","la cueva","la niebla","el granizo","el arcoíris","el relámpago","el rayo","el trueno","la raíz","la rama","el tronco","la semilla","el planeta","la costa","el pantano"},
                                   {"natura","caelum","nubes","sol","luna","lacus","flumen","mare","arbor","folium","flos","planta","herba","silva","mons","ventus","tempestas","imber","nix","tempestas","stella","-","-","-","vallis","insula","-","-","-","-","-","arcus pluvius","fulgur","fulmen","tonitrus","radix","ramus","-","-","-","-","-"} };
        public static string[,] city = {{"droga","park","pole","stolica","ulica","plac","sąsiad","most","miasto","wioska","poczta","kościół","biblioteka","muzeum","bank","szpital","posterunek policji","remiza strażacka","ratusz","teatr","kino","hotel","restauracja","chodnik","latarnia","przystanek","plac zabaw","parking","fontanna","pomnik","dzielnica","przedmieścia","osiedle","centrum","mieszkaniec","turysta","tłum","sklep","stacja benzynowa","cmentarz","rondo","sygnalizacja świetlna","korek","taksówka"},
                                  {"road","park","field","capital","street","square","neighbour","bridge","city","village","post office","church","library","museum","bank","hospital","police station","fire station","town hall","theatre","cinema","hotel","restaurant","pavement","street lamp","bus stop","playground","car park","fountain","monument","district","suburbs","housing estate","city centre","resident","tourist","crowd","shop","petrol station","cemetery","roundabout","traffic lights","traffic jam","taxi"},
                                  {"el camino","el parque","el campo","la capital","la calle","la plaza","el vecino","el puente","la ciudad","el pueblo","la oficina de correos","la iglesia","la biblioteca","el museo","el banco","el hospital","la comisaría","el parque de bomberos","el ayuntamiento","el teatro","el cine","el hotel","el restaurante","la acera","la farola","la parada de autobús","el parque infantil","el aparcamiento","la fuente","el monumento","el distrito","las afueras","la urbanización","el centro","el residente","el turista","la multitud","la tienda","la gasolinera","el cementerio","la rotonda","el semáforo","el atasco","el taxi"},
                                  {"via","-","ager","caput","vicus","forum","vicinus","pons","urbs","vicus","-","ecclesia","bibliotheca","-","-","-","-","-","-","theatrum","-","-","taberna","-","-","-","-","-","-","statua","-","suburbium","-","-","-","peregrinus","turba","taberna","-","sepulcrum","-","-","-","-"} };
        public static string[,] countries = {{"Brytyjczyk, brytyjski","Wielka Brytania (Zjednoczone Królestwo)","Japończyk, japoński","Japonia","Rosjanin, rosyjski","Rosja","Kanadyjczyk, kanadyjski","Kanada","Amerykanin, amerykański","Stany Zjednoczone Ameryki","Australijczyk, australijski","Australia","Grek, grecki","Grecja","Niemiec, niemiecki","Niemcy","Francuz, francuski","Francja","Hiszpan, hiszpański","Hiszpania","Włoch, włoski","Włochy","Polak, polski","Polska","Meksykanin, meksykański","Meksyk","Portugalczyk, portugalski","Portugalia","Chińczyk, chiński","Chiny","Irlandczyk, irlandzki","Irlandia","Brazylijczyk, brazylijski","Brazylia","Egipcjanin, egipski","Egipt","Hindus, indyjski","Indie","Europa","Azja","Afryka","Ameryka Północna","Ameryka Południowa","Oceania","kontynent","mapa","flaga","granica","ojczyzna","obcokrajowiec","narodowość","kraj","język","świat","obywatelstwo"},
                                            {"British","United Kingdom","Japanese","Japan","Russian","Russia","Canadian","Canada","American","United States of America","Australian","Australia","Greek","Greece","German","Germany","French","France","Spanish","Spain","Italian","Italy","Polish","Poland","Mexican","Mexico","Portuguese","Portugal","Chinese","China","Irish","Ireland","Brazilian","Brazil","Egyptian","Egypt","Indian","India","Europe","Asia","Africa","North America","South America","Oceania","continent","map","flag","border","homeland","foreigner","nationality","country","language","world","citizenship"},
                                            {"británico","el Reino Unido","japonés","Japón","ruso","Rusia","canadiense","Canadá","estadounidense","los Estados Unidos de América","australiano","Australia","griego","Grecia","alemán","Alemania","francés","Francia","español","España","italiano","Italia","polaco","Polonia","mexicano","México","portugués","Portugal","chino","China","irlandés","Irlanda","brasileño","Brasil","egipcio","Egipto","indio","India","Europa","Asia","África","América del Norte","América del Sur","Oceanía","el continente","el mapa","la bandera","la frontera","la patria","el extranjero","la nacionalidad","el país","el idioma","el mundo","la ciudadanía"},
                                            {"Britannus","Britannia","-","-","-","-","-","-","-","-","-","-","Graecus","Graecia","Germanus","Germania","Gallus","Gallia","Hispanus","Hispania","Italus","Italia","Polonus","Polonia","-","-","-","Lusitania","-","-","Hibernus","Hibernia","-","-","Aegyptius","Aegyptus","Indus","India","Europa","Asia","Africa","-","-","-","-","mappa","vexillum","-","patria","peregrinus","-","regio","lingua","mundus","civitas"} };

        private static string[,] descriptiveAdjectives = {{"łatwy","trudny","ważny","różny","taki sam","wolny (dostępny)","zajęty","pełny","pusty","blisko","daleko","możliwy","niemożliwy","duży","mały","długi","okrągły","kwadratowy","kształt","numer","metr","połowa"},
                                                           {"easy","difficult","important","different","same","free (available)","busy","full","empty","near","far","possible","impossible","big","small","long","round","square","shape","number","metre","half"},
                                                           {"fácil","difícil","importante","diferente","mismo","libre","ocupado","lleno","vacío","cerca","lejos","posible","imposible","grande","pequeño","largo","redondo","cuadrado","la forma","el número","el metro","la mitad"} };

        private static string[,] viewsComparisons = {{"zgadzać się","nie zgadzać się","moim zdaniem","myślę, że","mieć rację","mylić się","według mnie","zgoda!","masz rację","to zależy","więcej","mniej","najwięcej","najlepszy","najgorszy","tyle samo","kilka","wiele","mało"},
                                                      {"agree","disagree","in my opinion","I think that","be right","be wrong","in my view","agreed!","you're right","it depends","more","less","most","best","worst","the same amount","a few","a lot","little"},
                                                      {"estar de acuerdo","no estar de acuerdo","en mi opinión","creo que","tener razón","equivocarse","desde mi punto de vista","¡de acuerdo!","tienes razón","depende","más","menos","lo más","el mejor","el peor","la misma cantidad","unos pocos","mucho","poco"} };

        
        private static string[,] travel = {{"wycieczka","rower","prom","lotnisko","przystanek autobusowy","metro","bagaż","turysta","lot","jechać samochodem","wracać","autobus","pociąg","samochód","samolot","(po)wolny","szybki","skręcać","gubić"},
                                            {"trip","bike","ferry","airport","bus stop","underground","luggage","tourist","flight","drive","come back","bus","train","car","plane","slow","fast","turn","lose"},
                                            {"el viaje","la bicicleta","el ferry","el aeropuerto","la parada de autobús","el metro","el equipaje","el/la turista","el vuelo","conducir","volver","el autobús","el tren","el coche","el avión","lento","rápido","girar","perder"} };

        private static string[,] directionsTravel = {{"bilet","paszport","dworzec","iść","w lewo","w prawo","prosto","na rogu","przejście dla pieszych","skrzyżowanie","zakręt","róg (ulicy)","znak drogowy","chodnik"},
                                                      {"ticket","passport","station","go","left","right","straight ahead","on the corner","pedestrian crossing","crossroads","turn","corner (street)","road sign","pavement"},
                                                      {"el billete","el pasaporte","la estación","ir","a la izquierda","a la derecha","todo recto","en la esquina","el paso de peatones","el cruce","la curva","la esquina","la señal de tráfico","la acera"} };

        
        private static string[,] speakBasics = {{"imię","nad","obok","pomiędzy","przed","ale","też","pod","w","na","za","i, oraz","do widzenia","dziękuję","Jak się masz?","dobry wieczór","dzień dobry (przed południem)","dzień dobry (po południu)","przepraszam (za coś)","przepraszam (z zapytaniem)","proszę (o coś)","ponieważ","dlatego","jeśli","chociaż","więc","żeby"},
                                                {"name","over","next to","between","in front of","but","too","under","in","on","behind","and","goodbye","thank you","How are you?","good evening","good morning","good afternoon","sorry","excuse me","please","because","therefore","if","although","so","in order to"},
                                                {"el nombre","encima de","al lado de","entre","delante de","pero","también","debajo de","en","en","detrás de","y","adiós","gracias","¿Cómo estás?","buenas noches","buenos días","buenas tardes","lo siento","perdón","por favor","porque","por eso","si","aunque","así que","para"} };

        private static string[,] pronounsBasics = {{"ja","ty (wy)","to","on","ona","my","oni (one)","tak","nie","mieć","dobry","cześć","zły","chcieć","brać","robić (np. ciasto, zupę)"},
                                                    {"I","you","it","he","she","we","they","yes","no","have","good","hello","bad","want","take","make"},
                                                    {"yo","tú (vosotros)","eso","él","ella","nosotros","ellos (ellas)","sí","no","tener","bueno","hola","malo","querer","tomar","hacer"} };

        private static string[,] questionsVerbs = {{"wspaniały","Ile? (policzalne)","Kto?","Co?","znać, wiedzieć","Gdzie?","Jak?","mówić, przemawiać","nie ma za co","Dlaczego?","mieszkać","być","robić (np. zakupy, ćwiczenie)","Ile? (niepoliczalne)","Kiedy?","dawać"},
                                                   {"great","How many?","Who?","What?","know","Where?","How?","speak","you are welcome","Why?","live","be","do","How much?","When?","give"},
                                                   {"genial","¿Cuántos?","¿Quién?","¿Qué?","saber","¿Dónde?","¿Cómo?","hablar","de nada","¿Por qué?","vivir","ser","hacer","¿Cuánto?","¿Cuándo?","dar"} };

        private static string[,] appearance = {{"przystojny","stary","młody","ładny","elegancki","wysoki","niski","czysty","prosty","kręcony","brudny","piękny","brzydki","gruby","szczupły"},
                                                {"handsome","old","young","pretty","elegant","tall","short","clean","straight","curly","dirty","beautiful","ugly","fat","slim"},
                                                {"guapo","viejo","joven","bonito","elegante","alto","bajo","limpio","liso","rizado","sucio","hermoso","feo","gordo","delgado"} };

        
        private static string[,] leisureHolidays = {{"relaksować się","śpiewać","pływać","przyjęcie, impreza","bawić się","zainteresowania","robić zdjęcia","wakacje","malować","słuchać","czytać","kino","teatr","koncert","oglądać","uprawiać sporty","biegać","tańczyć","plaża","piasek","fala","kąpiel słoneczna","krem do opalania","opalać się","zamek z piasku"},
                                                     {"relax","sing","swim","party","play","hobbies","take photos","holiday","paint","listen","read","cinema","theatre","concert","watch","do sports","run","dance","beach","sand","wave","sunbathing","sunscreen","to sunbathe","sandcastle"},
                                                     {"relajarse","cantar","nadar","la fiesta","jugar","los intereses","hacer fotos","las vacaciones","pintar","escuchar","leer","el cine","el teatro","el concierto","ver","hacer deporte","correr","bailar","la playa","la arena","la ola","el baño de sol","la crema solar","tomar el sol","el castillo de arena"} };

        private static string[,] sportsMusic = {{"piłka nożna","koszykówka","tenis","pływanie","siatkówka","narciarstwo","jazda konna","gitara","pianino","skrzypce","grać na (instrumencie)","mecz","drużyna","trener"},
                                                 {"football","basketball","tennis","swimming","volleyball","skiing","horse riding","guitar","piano","violin","play (an instrument)","match","team","coach"},
                                                 {"el fútbol","el baloncesto","el tenis","la natación","el voleibol","el esquí","la equitación","la guitarra","el piano","el violín","tocar (un instrumento)","el partido","el equipo","el entrenador"} };

        private static string[,] technologyMedia = {{"internet","hasło","konto","aplikacja","wiadomość","e-mail","link","ładować (telefon)","wifi","strona internetowa","przeglądarka","klikać","logować się","wylogowywać się","pobierać","wysyłać","media społecznościowe","aktualizować","telewizja","radio","gazeta","wiadomości (news)","reklama","program (telewizyjny)"},
                                                     {"internet","password","account","app","message","email","link","charge (phone)","wifi","website","browser","click","log in","log out","download","send","social media","update","television","radio","newspaper","news","advertisement","TV programme"},
                                                     {"el internet","la contraseña","la cuenta","la aplicación","el mensaje","el correo electrónico","el enlace","cargar (el teléfono)","el wifi","el sitio web","el navegador","hacer clic","iniciar sesión","cerrar sesión","descargar","enviar","las redes sociales","actualizar","la televisión","la radio","el periódico","las noticias","el anuncio","el programa"} };

        private static string[,] feelings = {{"zmęczony","bać się","płakać","śmiać się","uśmiechać się","zdenerwowany","senny","zły (na kogoś)","smutny","szczęśliwy","nienawidzić","kochać","lubić","dumny","nudny","zaskakiwać","uczucie","myśleć","martwić się","rozczarowany","zaskoczony","zestresowany","zrelaksowany","zazdrosny"},
                                             {"tired","be scared","cry","laugh","smile","nervous","sleepy","angry","sad","happy","hate","love","like","proud","boring","surprise","feeling","think","worry","disappointed","surprised","stressed","relaxed","jealous"},
                                             {"cansado","tener miedo","llorar","reír","sonreír","nervioso","tener sueño","enfadado","triste","feliz","odiar","amar","gustar","orgulloso","aburrido","sorprender","el sentimiento","pensar","preocuparse","decepcionado","sorprendido","estresado","relajado","celoso"} };

        private static string[,] shopping = {{"portfel","centrum handlowe","księgarnia","piekarnia","drogi","tani","płacić","bankomat","sklep","sprzedawać","pieniądze","targ","cena","koszyk","półka","reszta","kupować","zakupy"},
                                              {"wallet","shopping center","bookshop","bakery","expensive","cheap","pay","cashpoint","shop","sell","money","market","price","basket","shelf","change","buy","shopping"},
                                              {"la cartera","el centro comercial","la librería","la panadería","caro","barato","pagar","el cajero automático","la tienda","vender","el dinero","el mercado","el precio","la cesta","la estantería","el cambio","comprar","las compras"} };

        private static string[,] moneyDining = {{"zamawiać","rachunek","kelner","menu","napiwek","stolik (rezerwacja)","rezerwacja","danie","przystawka","danie główne","konto bankowe","przelew","oszczędzać","pożyczać","rachunek (do zapłacenia)","gotówka","karta kredytowa","karta debetowa","oprocentowanie","kredyt","zadłużenie","wydawać (pieniądze)","budżet","waluta"},
                                                 {"order","bill","waiter","menu","tip","table (reservation)","reservation","dish","starter","main course","bank account","transfer","save (money)","borrow","bill (to pay)","cash","credit card","debit card","interest rate","loan","debt","spend (money)","budget","currency"},
                                                 {"pedir","la cuenta","el camarero","el menú","la propina","la mesa (reserva)","la reserva","el plato","el entrante","el plato principal","la cuenta bancaria","la transferencia","ahorrar","pedir prestado","la factura","el efectivo","la tarjeta de crédito","la tarjeta de débito","el tipo de interés","el préstamo","la deuda","gastar","el presupuesto","la moneda"} };

        private static string[,] professions = {{"muzyk","malarz","naukowiec","policjant","strażak","pielęgniarka","architekt","sekretarka","mechanik","informatyk","programista","inżynier","aktor","artysta","lekarz","dziennikarz","sprzedawca","fryzjer","prawnik"},
                                                 {"musician","painter","scientist","police officer","fireman","nurse","architect","secretary","mechanic","IT specialist","computer programmer","engineer","actor","artist","doctor","journalist","shop assistant","hairdresser","lawyer"},
                                                 {"el músico","el pintor","el científico","el policía","el bombero","la enfermera","el arquitecto","la secretaria","el mecánico","el informático","el programador","el ingeniero","el actor","el artista","el médico","el periodista","el vendedor","el peluquero","el abogado"} };

        private static string[,] officeComputer = {{"dzwonić","kopiować","ekran","plik, dokument","klawiatura","telefon komórkowy","drukować","zapisywać","włączać","wyłączać","praca","biuro","komputer","szef","CV","rozmowa kwalifikacyjna","umowa o pracę","pensja","urlop","zwolnienie (z pracy)","awans","doświadczenie (zawodowe)"},
                                                    {"phone","copy","screen","file","keyboard","mobile phone","print","save","turn on","turn off","work","office","computer","boss","CV","job interview","employment contract","salary","holiday leave","dismissal","promotion","experience"},
                                                    {"llamar","copiar","la pantalla","el archivo","el teclado","el móvil","imprimir","guardar","encender","apagar","el trabajo","la oficina","el ordenador","el jefe","el currículum","la entrevista de trabajo","el contrato de trabajo","el salario","las vacaciones","el despido","el ascenso","la experiencia"} };

        private static string[,] character = {{"arogancki","radosny","nieśmiały","szalony","uparty","inteligentny","spokojny","towarzyski","odważny","miły","sympatyczny","uczciwy","mądry","cierpliwy","samolubny"},
                                               {"rude","cheerful","shy","crazy","stubborn","intelligent","calm","outgoing","brave","nice","friendly","honest","clever","patient","selfish"},
                                               {"arrogante","alegre","tímido","loco","testarudo","inteligente","tranquilo","sociable","valiente","amable","simpático","honesto","listo","paciente","egoísta"} };

        private static string[,] health = {{"pigułka, tabletka","choroba","chory","zdrowy","lekarstwo","karetka","apteka","łamać","kaszel","przeziębić się","grypa","gorączka","umawiać się (na wizytę)","ból","boleć","ból głowy","ból gardła","czuć się","szpital"},
                                            {"pill","illness","sick","healthy","medicine","ambulance","pharmacy","break","cough","catch a cold","flu","fever","make an appointment","pain","hurt","headache","sore throat","feel","hospital"},
                                            {"la pastilla","la enfermedad","enfermo","sano","el medicamento","la ambulancia","la farmacia","romper","la tos","resfriarse","la gripe","la fiebre","pedir cita","el dolor","doler","el dolor de cabeza","el dolor de garganta","sentirse","el hospital"} };

        private static string[,] emergencies = {{"Pomocy!","pożar","niebezpieczeństwo","wzywać (pomoc/policję)","alarm","wypadek","policja","straż pożarna","ratować","uciekać","ostrożnie!","zagrożenie"},
                                                 {"Help!","fire","danger","call (for help/police)","alarm","accident","police","fire brigade","save/rescue","escape","careful!","threat"},
                                                 {"¡Socorro!","el incendio","el peligro","llamar (a la policía)","la alarma","el accidente","la policía","los bomberos","salvar","escapar","¡cuidado!","la amenaza"} };

        private static string[,] celebrations = {{"Boże Narodzenie","Wielkanoc","urodziny","prezent","świętować","życzenia","choinka","fajerwerki","Nowy Rok","imieniny","gratulacje","zapraszać","gość","tort urodzinowy"},
                                                  {"Christmas","Easter","birthday","present","celebrate","wishes","Christmas tree","fireworks","New Year","name day","congratulations","invite","guest","birthday cake"},
                                                  {"la Navidad","la Pascua","el cumpleaños","el regalo","celebrar","los deseos","el árbol de Navidad","los fuegos artificiales","el Año Nuevo","el santo","las felicidades","invitar","el invitado","la tarta de cumpleaños"} };

        private static string[,] verbsActions = {{"potrzebować","szukać","znajdować","pomagać","zaczynać","kończyć","kontynuować","przestawać","pamiętać","zapominać","próbować","wyjaśniać","pytać","odpowiadać","wybierać","decydować się","obiecywać","mieć nadzieję"},
                                                  {"need","look for","find","help","start","finish","continue","stop","remember","forget","try","explain","ask","answer","choose","decide","promise","hope"},
                                                  {"necesitar","buscar","encontrar","ayudar","empezar","terminar","continuar","parar","recordar","olvidar","intentar","explicar","preguntar","responder","elegir","decidir","prometer","esperar"} };

        public static string[,] GetFiszki(string nazwa) => (string[,])typeof(Fiszki).GetField(nazwa)!.GetValue(null)!;
        public static string[][,] Kategorie = { numbers, wordsMath, colors, animalsHome, animalsWild, animalWords, kitchen, bathroom, livingBedroom, buildingGeneral,
                                         vegetables, fruits, farmCrops, soups, mainDishes, otherDishes, pantry, drinks, spices, bakedSweets,
                                         fish, mushrooms, mealWordsDescriptions, familyCore, familyExtended, familyStatus, familyVerbs, timeUnitsMeasure, timeDayParts, timeCalendar,
                                         timeAdverbs, body, clothes, materials, school, nature, city, countries };
        public static string[][,] KategorieRobocze = { numbers, wordsMath, colors, animalsHome, animalsWild, animalWords };
    }
}