namespace Dziekanowka.Mechanizm.JezykiObce
{
    public class Fiszki
    {
        private static string[,] numbers = {{"zero","jeden","dwa","trzy","cztery","pięć","sześć","siedem","osiem","dziewięć","dziesięć","jedenaście","dwanaście","trzynaście","czternaście","piętnaście","szesnaście","siedemnaście","osiemnaście","dziewiętnaście","dwadzieścia","trzydzieści","czterdzieści","pięćdziesiąt","sześćdziesiąt","siedemdziesiąt","osiemdziesiąt","dziewięćdziesiąt","sto","tysiąc","milion","pierwszy","drugi","trzeci","czwarty","piąty","ostatni"},
                                    {"zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety","hundred","thousand","million","first","second","third","fourth","fifth","last"},
                                    {"cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve","diez","once","doce","trece","catorce","quince","dieciséis","diecisiete","dieciocho","diecinueve","veinte","treinta","cuarenta","cincuenta","sesenta","setenta","ochenta","noventa","cien","mil","millón","primero","segundo","tercero","cuarto","quinto","último"},
                                    {"nulla","unus","duo","tres","quattuor","quinque","sex","septem","octo","novem","decem","undecim","duodecim","tredecim","quattuordecim","quindecim","sedecim","septendecim","duodeviginti","undeviginti","viginti","triginta","quadraginta","quinquaginta","sexaginta","septuaginta","octoginta","nonaginta","centum","mille","decies centena milia","primus","secundus","tertius","quartus","quintus","ultimus"} };
        private static string[,] wordsMath = {{"numer","liczba","połowa","ćwiartka","całość","więcej","mniej","tyle samo","kilka","wiele","mało","liczyć","obliczać","podwoić","parzysty","nieparzysty","suma","różnica","iloczyn","iloraz","cyfra","dodawać","odejmować","mnożyć","dzielić","równać się","procent","wynik","ułamek"},
                                      {"number","number","half","quarter","whole","more","less","the same amount","a few","a lot","little","count","calculate","double","even","odd","sum","difference","product","quotient","digit","add","subtract","multiply","divide","equal","percent","result","fraction"},
                                      {"el número","el número","la mitad","el cuarto","el todo","más","menos","la misma cantidad","unos pocos","mucho","poco","contar","calcular","duplicar","par","impar","la suma","la diferencia","el producto","el cociente","la cifra","sumar","restar","multiplicar","dividir","ser igual a","el porcentaje","el resultado","la fracción"},
                                      {"numerus","numerus","dimidium","quadrans","totum","plus","minus","tantundem","aliquot","multum","paucum","numerare","computare","duplicare","par","impar","summa","differentia","productus","-","digitus","addere","subtrahere","multiplicare","dividere","aequare","-","eventus","-"} };
        private static string[,] colors = {{"czarny","biały","czerwony","żółty","zielony","niebieski","szary","różowy","pomarańczowy","brązowy","fioletowy","kolor","złoty","srebrny"},
                                    {"black","white","red","yellow","green","blue","grey","pink","orange","brown","purple","colour","gold","silver"},
                                    {"negro","blanco","rojo","amarillo","verde","azul","gris","rosa","naranja","marrón","morado","el color","dorado","plateado"},
                                    {"niger","albus","ruber","flavus","viridis","caeruleus","canus","roseus","-","fulvus","purpureus","color","aureus","argenteus"} };
        private static string[,] animalsHome = {{"kot","pies","ryba","chomik","papuga","krowa","koń","kaczka","osioł","kura","świnia","owca","kogut","indyk","koza","gęś","żółw","ptak","ślimak","motyl","mucha","mysz","pszczoła","królik","komar"},
                                         {"cat","dog","fish","hamster","parrot","cow","horse","duck","donkey","hen","pig","sheep","rooster","turkey","goat","goose","turtle","bird","snail","butterfly","fly","mouse","bee","rabbit","mosquito"},
                                         {"el gato","el perro","el pez","el hámster","el loro","la vaca","el caballo","el pato","el burro","la gallina","el cerdo","la oveja","el gallo","el pavo","la cabra","el ganso","la tortuga","el pájaro","el caracol","la mariposa","la mosca","el ratón","la abeja","el conejo","el mosquito"},
                                         {"felis","canis","piscis","-","psittacus","bos","equus","anas","asinus","gallina","porcus","ovis","gallus","-","capra","anser","testudo","avis","cochlea","papilio","musca","mus","apis","cuniculus","culex"} };
        private static string[,] animalsWild = {{"lew","słoń","wilk","lis","żaba","tygrys","niedźwiedź","wąż","żyrafa","zebra","kangur","delfin","wieloryb","rekin","orzeł","sowa","jeleń","sarna","hipopotam","nosorożec"},
                                         {"lion","elephant","wolf","fox","frog","tiger","bear","snake","giraffe","zebra","kangaroo","dolphin","whale","shark","eagle","owl","deer","roe deer","hippopotamus","rhinoceros"},
                                         {"el león","el elefante","el lobo","el zorro","la rana","el tigre","el oso","la serpiente","la jirafa","la cebra","el canguro","el delfín","la ballena","el tiburón","el águila","el búho","el ciervo","el corzo","el hipopótamo","el rinoceronte"},
                                         {"leo","elephantus","lupus","vulpes","rana","tigris","ursus","serpens","-","-","-","delphinus","balaena","-","aquila","-","cervus","-","hippopotamus","rhinoceros"} };
        private static string[,] animalWords = {{"zwierzę","zwierzak domowy","szczekać","miauczeć","głaskać","dziki","oswojony","futro","sierść","pióra","łapa","ogon","skrzydło","rżeć","muczeć","beczeć","kwakać","ryczeć","róg","kieł","pazur","grzywa","polować","wysiadywać (jaja)","znosić jajka","stado","gniazdo","nora"},
                                        {"animal","pet","bark","meow","stroke/pet","wild","tame","fur","coat (animal hair)","feathers","paw","tail","wing","neigh","moo","bleat","quack","roar","horn","fang/tusk","claw","mane","hunt","hatch/incubate","lay eggs","herd/flock","nest","burrow/den"},
                                        {"el animal","la mascota","ladrar","maullar","acariciar","salvaje","domesticado","el pelaje","el pelo","las plumas","la pata","la cola","el ala","relinchar","mugir","balar","graznar","rugir","el cuerno","el colmillo","la garra","la melena","cazar","incubar","poner huevos","la manada","el nido","la madriguera"},
                                        {"animal","-","latrare","-","-","ferus","domesticus","pellis","-","pluma","-","cauda","ala","hinnire","mugire","balare","-","rugire","cornu","dens","unguis","iuba","venari","-","-","grex","nidus","-"} };
        private static string[,] kitchen = {{"lodówka","zlew","kuchnia","zmywać naczynia","kroić","smażyć","gotować się (wrzeć)","mieszać","obierać","piec","dodawać","ważyć","siekać","podgrzewać","talerz","widelec","nóż","łyżka","łyżeczka","szklanka","kubek","filiżanka","serwetka","obrus","garnek","patelnia","piekarnik","kuchenka (płyta)","mikrofalówka","zmywarka","czajnik","deska do krojenia"},
                                        {"fridge","sink","kitchen","wash the dishes","cut","fry","boil","mix","peel","bake","add","weigh","chop","heat up","plate","fork","knife","spoon","teaspoon","glass","mug","cup","napkin","tablecloth","pot","pan","oven","stove/hob","microwave","dishwasher","kettle","cutting board"},
                                        {"la nevera","el fregadero","la cocina","fregar los platos","cortar","freír","hervir","mezclar","pelar","hornear","añadir","pesar","picar","calentar","el plato","el tenedor","el cuchillo","la cuchara","la cucharilla","el vaso","la taza","la taza","la servilleta","el mantel","la olla","la sartén","el horno","la placa de cocina","el microondas","el lavavajillas","el hervidor","la tabla de cortar"},
                                        {"-","-","culina","vasa lavare","secare","frigere","fervere","miscere","-","coquere","addere","ponderare","concidere","calefacere","catinus","-","culter","cochlear","-","poculum","-","-","mappa","mantele","olla","-","furnus","-","-","-","-","-"} };
        private static string[,] bathroom = {{"prysznic","wanna","lustro","łazienka","czesać się","myć","pralka","wieszać pranie","toaleta","umywalka","ręcznik","mydło","szampon","pasta do zębów","szczoteczka do zębów","myć zęby","kąpać się","golić się","suszarka do włosów","papier toaletowy","szczotka do włosów","golarka"},
                                          {"shower","bathtub","mirror","bathroom","comb","wash","washing machine","hang out the laundry","toilet","sink (bathroom)","towel","soap","shampoo","toothpaste","toothbrush","brush teeth","bathe","shave","hair dryer","toilet paper","hairbrush","razor"},
                                          {"la ducha","la bañera","el espejo","el baño","peinarse","lavar","la lavadora","tender la ropa","el aseo","el lavabo","la toalla","el jabón","el champú","la pasta de dientes","el cepillo de dientes","cepillarse los dientes","bañarse","afeitarse","el secador de pelo","el papel higiénico","el cepillo del pelo","la maquinilla de afeitar"},
                                          {"-","alveus","speculum","balneum","se pectere","lavare","-","-","latrina","-","linteum","sapo","-","-","-","dentes fricare","lavari","se radere","-","-","-","novacula"} };
        private static string[,] livingBedroom = {{"szafa","książka","regał","stół","krzesło","telewizor","fotel","łóżko","kanapa","dywan","salon","sypialnia","zasłony","ścielić łóżko","ścierać kurz","budzić się","spać","sprzątać","odkurzać","prasować","zamiatać","lampa","poduszka","kołdra","pościel","budzik"},
                                           {"wardrobe","book","bookshelf","table","chair","TV","armchair","bed","sofa","carpet","living room","bedroom","curtains","make the bed","dust","wake up","sleep","clean/tidy up","vacuum","iron","sweep","lamp","pillow","duvet","bedding","alarm clock"},
                                           {"el armario","el libro","la estantería","la mesa","la silla","el televisor","el sillón","la cama","el sofá","la alfombra","el salón","el dormitorio","las cortinas","hacer la cama","quitar el polvo","despertarse","dormir","limpiar","pasar la aspiradora","planchar","barrer","la lámpara","la almohada","el edredón","la ropa de cama","el despertador"},
                                           {"armarium","liber","pluteus","mensa","sella","-","-","lectus","-","tapete","-","cubiculum","vela","-","-","expergisci","dormire","-","-","-","verrere","lucerna","pulvinus","-","-","-"} };
        private static string[,] buildingGeneral = {{"klucz","pokój","okno","ściana","podłoga","parter","drzwi","sufit","garaż","piwnica","adres","dom","mieszkanie","mieszkać","piętro","balkon","taras","schody","winda","strych","żarówka","grzejnik","wynosić śmieci","skrzynka pocztowa","dzwonek","remontować"},
                                             {"key","room","window","wall","floor","ground floor","door","ceiling","garage","cellar","address","house","flat","live","storey","balcony","terrace","stairs","lift","attic","lightbulb","radiator","take out the rubbish","mailbox","doorbell","renovate"},
                                             {"la llave","la habitación","la ventana","la pared","el suelo","la planta baja","la puerta","el techo","el garaje","el sótano","la dirección","la casa","el piso","vivir","la planta","el balcón","la terraza","las escaleras","el ascensor","el desván","la bombilla","el radiador","sacar la basura","el buzón","el timbre","reformar"},
                                             {"clavis","conclave","fenestra","paries","solum","-","ianua","lacunar","-","cella","-","domus","-","habitare","-","-","solarium","scalae","-","-","-","-","-","-","-","renovare"} };
		private static string[,] vegetables = {{"groch","jarmuż","pasternak","pietruszka","burak","brukselka","sałata","marchew","ziemniak","cebula","szczypiorek","pomidor","papryka","ogórek","czosnek","rzodkiewka","szpinak","rukola","batat","szczaw","seler","boćwina","por","fasola","bób","ciecierzyca","bakłażan","cukinia","dynia","brokuł","kalafior","kapusta włoska","kapusta pekińska","szparagi","seler naciowy","soczewica"},
                                       {"pea","kale","parsnip","parsley","beetroot","Brussels sprout","lettuce","carrot","potato","onion","chives","tomato","pepper","cucumber","garlic","radish","spinach","rocket/arugula","sweet potato","sorrel","celery","chard","leek","beans","broad bean","chickpea","eggplant","courgette/zucchini","pumpkin","broccoli","cauliflower","Savoy cabbage","Chinese cabbage","asparagus","celery (stalk)","lentil"},
                                       {"el guisante","la berza","la chirivía","el perejil","la remolacha","la col de Bruselas","la lechuga","la zanahoria","la patata","la cebolla","el cebollino","el tomate","el pimiento","el pepino","el ajo","el rábano","la espinaca","la rúcula","el boniato","la acedera","el apio","la acelga","el puerro","las judías","las habas","el garbanzo","la berenjena","el calabacín","la calabaza","el brócoli","la coliflor","la col de Milán","la col china","los espárragos","el apio","la lenteja"},
                                       {"pisum","-","pastinaca","petroselinum","beta","-","lactuca","carota","-","cepa","-","-","-","cucumis","allium","raphanus","-","eruca","-","rumex","apium","-","porrum","phaseolus","faba","cicer","-","-","cucurbita","-","-","-","-","asparagus","apium","lens"} };
		private static string[,] fruits = {{"brzoskwinia","nektarynka","morela","śliwka","wiśnia","czereśnia","jabłko","gruszka","truskawka","malina","jeżyna","borówka","porzeczka czerwona","porzeczka czarna","żurawina","pomarańcza","mandarynka","cytryna","grejpfrut","banan","ananas","mango","papaja","marakuja","kokos","awokado","arbuz","melon","winogrono jasne","winogrono różowe","winogrono ciemne","kiwi","figa","granat","agrest","daktyl"},
                                    {"peach","nectarine","apricot","plum","sour cherry","sweet cherry","apple","pear","strawberry","raspberry","blackberry","blueberry","redcurrant","blackcurrant","cranberry","orange","tangerine/mandarin","lemon","grapefruit","banana","pineapple","mango","papaya","passion fruit","coconut","avocado","watermelon","melon","light grapes","pink grapes","dark grapes","kiwi","fig","pomegranate","gooseberry","date"},
                                    {"el melocotón","la nectarina","el albaricoque","la ciruela","la guinda","la cereza","la manzana","la pera","la fresa","la frambuesa","la mora","el arándano","la grosella roja","la grosella negra","el arándano rojo","la naranja","la mandarina","el limón","el pomelo","el plátano","la piña","el mango","la papaya","la maracuyá","el coco","el aguacate","la sandía","el melón","la uva blanca","la uva rosada","la uva negra","el kiwi","el higo","la granada","la grosella espinosa","el dátil"},
                                    {"malum persicum","-","malum armeniacum","prunum","cerasum","cerasum","malum","pirum","fragum","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","melopepo","uva","uva","uva","-","ficus","malum punicum","-","dactylus"} };
		private static string[,] farmCrops = {{"żyto","jęczmień","pszenica","ryż","owies","gryka","orkisz","koniczyna","rzepa pastewna","sorgo","kukurydza","proso","len","rzepak","słonecznik","chmiel","konopia","mak","soja","bawełna","trzcina cukrowa","komosa ryżowa"},
                                      {"rye","barley","wheat","rice","oats","buckwheat","spelt","clover","fodder turnip","sorghum","corn/maize","millet","flax","rapeseed","sunflower","hops","hemp","poppy","soybean","cotton","sugar cane","quinoa"},
                                      {"el centeno","la cebada","el trigo","el arroz","la avena","el trigo sarraceno","la escanda","el trébol","el nabo forrajero","el sorgo","el maíz","el mijo","el lino","la colza","el girasol","el lúpulo","el cáñamo","la amapola","la soja","el algodón","la caña de azúcar","la quinoa"},
                                      {"secale","hordeum","triticum","oryza","avena","-","far","trifolium","napus","-","-","panicum","linum","-","-","-","cannabis","papaver","-","-","-","-"} };
		private static string[,] soups = {{"rosół","barszcz czerwony","żurek","krupnik","zupa pomidorowa","zupa ogórkowa","zupa grzybowa","kapuśniak","grochówka","zupa fasolowa","zupa cebulowa","chłodnik","krem z brokułów","krem z dyni","krem z kalafiora","zupa jarzynowa","zupa mleczna","flaki","zupa szczawiowa","zupa rybna"},
                                   {"chicken/meat broth","beetroot soup","sour rye soup","barley soup","tomato soup","cucumber soup","mushroom soup","cabbage soup","pea soup","bean soup","onion soup","cold beetroot soup","broccoli cream soup","pumpkin cream soup","cauliflower cream soup","vegetable soup","milk soup","tripe soup","sorrel soup","fish soup"},
                                   {"el caldo de pollo","la sopa de remolacha","el żurek","la sopa de cebada","la sopa de tomate","la sopa de pepino","la sopa de champiñones","la sopa de col","la sopa de guisantes","la sopa de judías","la sopa de cebolla","la sopa fría de remolacha","la crema de brócoli","la crema de calabaza","la crema de coliflor","la sopa de verduras","la sopa de leche","los callos","la sopa de acedera","la sopa de pescado"},
                                   {"ius","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-","-"} };
        
        private static string[,] descriptiveAdjectives = {{"łatwy","trudny","ważny","różny","taki sam","wolny (dostępny)","zajęty","pełny","pusty","blisko","daleko","możliwy","niemożliwy","duży","mały","długi","okrągły","kwadratowy","kształt","numer","metr","połowa"},
                                                           {"easy","difficult","important","different","same","free (available)","busy","full","empty","near","far","possible","impossible","big","small","long","round","square","shape","number","metre","half"},
                                                           {"fácil","difícil","importante","diferente","mismo","libre","ocupado","lleno","vacío","cerca","lejos","posible","imposible","grande","pequeño","largo","redondo","cuadrado","la forma","el número","el metro","la mitad"} };

        private static string[,] viewsComparisons = {{"zgadzać się","nie zgadzać się","moim zdaniem","myślę, że","mieć rację","mylić się","według mnie","zgoda!","masz rację","to zależy","więcej","mniej","najwięcej","najlepszy","najgorszy","tyle samo","kilka","wiele","mało"},
                                                      {"agree","disagree","in my opinion","I think that","be right","be wrong","in my view","agreed!","you're right","it depends","more","less","most","best","worst","the same amount","a few","a lot","little"},
                                                      {"estar de acuerdo","no estar de acuerdo","en mi opinión","creo que","tener razón","equivocarse","desde mi punto de vista","¡de acuerdo!","tienes razón","depende","más","menos","lo más","el mejor","el peor","la misma cantidad","unos pocos","mucho","poco"} };

        
        private static string[,] timeUnits = {{"czas","noc","rano","popołudnie","wieczór","pora roku","rok","miesiąc","tydzień","dzień","godzina","minuta","sekunda"},
                                               {"time","night","morning","afternoon","evening","season","year","month","week","day","hour","minute","second"},
                                               {"el tiempo","la noche","la mañana","la tarde","el atardecer","la estación","el año","el mes","la semana","el día","la hora","el minuto","el segundo"} };

        private static string[,] timeAdverbsPrepositions = {{"dzisiaj","wczoraj","jutro","następny","codziennie","nigdy","zawsze","zwykle","czasami","rzadko","ostatnio","podczas","od (czasu)","do (czasu)","temu","przed (czasem)","po (czasie)"},
                                                             {"today","yesterday","tomorrow","next","every day","never","always","usually","sometimes","rarely","recently","during","since","until","ago","before (time)","after (time)"},
                                                             {"hoy","ayer","mañana","siguiente","todos los días","nunca","siempre","normalmente","a veces","raramente","recientemente","durante","desde","hasta","hace","antes de","después de"} };

        private static string[,] timeCalendar = {{"poniedziałek","wtorek","środa","czwartek","piątek","sobota","niedziela","styczeń","luty","marzec","kwiecień","maj","czerwiec","lipiec","sierpień","wrzesień","październik","listopad","grudzień","wiosna","lato","jesień","zima"},
                                                  {"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday","January","February","March","April","May","June","July","August","September","October","November","December","spring","summer","autumn","winter"},
                                                  {"el lunes","el martes","el miércoles","el jueves","el viernes","el sábado","el domingo","enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre","la primavera","el verano","el otoño","el invierno"} };

        private static string[,] familyCore = {{"rodzina","ojciec","matka","córka","syn","rodzic","mężczyzna","kobieta","mąż","żona","dziecko","brat","siostra","babcia","dziadek"},
                                                {"family","father","mother","daughter","son","parent","man","woman","husband","wife","child","brother","sister","grandmother","grandfather"},
                                                {"la familia","el padre","la madre","la hija","el hijo","el padre/la madre","el hombre","la mujer","el marido","la esposa","el niño","el hermano","la hermana","la abuela","el abuelo"} };

        private static string[,] familyRelationships = {{"wujek","ciocia","chłopiec","dziewczynka","kuzyn","chłopak (sympatia)","dziewczyna (sympatia)","rozwiedziony","żonaty/mężatka","ślub","być razem","wdowa","przyjaciel","urodzić się"},
                                                         {"uncle","aunt","boy","girl","cousin","boyfriend","girlfriend","divorced","married","wedding","be together","widow","friend","be born"},
                                                         {"el tío","la tía","el niño","la niña","el primo","el novio","la novia","divorciado","casado/casada","la boda","estar juntos","la viuda","el amigo","nacer"} };

        
        private static string[,] dailyRoutineChores = {{"spóźniać się","ścielić łóżko","czesać się","ścierać kurz","myć","budzić się","spać","śpieszyć się","sprzątać","zmywać naczynia","odkurzać","prasować","wieszać pranie","zamiatać","wynosić śmieci"},
                                                        {"be late","make the bed","comb","dust","wash","wake up","sleep","hurry","clean/tidy up","wash the dishes","vacuum","iron","hang out the laundry","sweep","take out the rubbish"},
                                                        {"llegar tarde","hacer la cama","peinarse","quitar el polvo","lavar","despertarse","dormir","darse prisa","limpiar","fregar los platos","pasar la aspiradora","planchar","tender la ropa","barrer","sacar la basura"} };

        private static string[,] travel = {{"wycieczka","rower","prom","lotnisko","przystanek autobusowy","metro","bagaż","turysta","lot","jechać samochodem","wracać","autobus","pociąg","samochód","samolot","(po)wolny","szybki","skręcać","gubić"},
                                            {"trip","bike","ferry","airport","bus stop","underground","luggage","tourist","flight","drive","come back","bus","train","car","plane","slow","fast","turn","lose"},
                                            {"el viaje","la bicicleta","el ferry","el aeropuerto","la parada de autobús","el metro","el equipaje","el/la turista","el vuelo","conducir","volver","el autobús","el tren","el coche","el avión","lento","rápido","girar","perder"} };

        private static string[,] directionsTravel = {{"bilet","paszport","dworzec","iść","w lewo","w prawo","prosto","na rogu","przejście dla pieszych","skrzyżowanie","zakręt","róg (ulicy)","znak drogowy","chodnik"},
                                                      {"ticket","passport","station","go","left","right","straight ahead","on the corner","pedestrian crossing","crossroads","turn","corner (street)","road sign","pavement"},
                                                      {"el billete","el pasaporte","la estación","ir","a la izquierda","a la derecha","todo recto","en la esquina","el paso de peatones","el cruce","la curva","la esquina","la señal de tráfico","la acera"} };

        
        private static string[,] speakBasics = {{"imię","nad","obok","pomiędzy","przed","ale","też","pod","w","na","za","i, oraz","do widzenia","dziękuję","Jak się masz?","dobry wieczór","dzień dobry (przed południem)","dzień dobry (po południu)","przepraszam (za coś)","przepraszam (z zapytaniem)","proszę (o coś)","ponieważ","dlatego","jeśli","chociaż","więc","żeby"},
                                                {"name","over","next to","between","in front of","but","too","under","in","on","behind","and","goodbye","thank you","How are you?","good evening","good morning","good afternoon","sorry","excuse me","please","because","therefore","if","although","so","in order to"},
                                                {"el nombre","encima de","al lado de","entre","delante de","pero","también","debajo de","en","en","detrás de","y","adiós","gracias","¿Cómo estás?","buenas noches","buenos días","buenas tardes","lo siento","perdón","por favor","porque","por eso","si","aunque","así que","para"} };

        private static string[,] pronounsBasics = {{"ja","ty (wy)","to","on","ona","my","oni (one)","tak","nie","mieć","dobry","cześć","zły","chcieć","brać","robić (np. ciasto, zupę)"},
                                                    {"I","you","it","he","she","we","they","yes","no","have","good","hello","bad","want","take","make"},
                                                    {"yo","tú (vosotros)","eso","él","ella","nosotros","ellos (ellas)","sí","no","tener","bueno","hola","malo","querer","tomar","hacer"} };

        private static string[,] questionsVerbs = {{"wspaniały","Ile? (policzalne)","Kto?","Co?","znać, wiedzieć","Gdzie?","Jak?","mówić, przemawiać","nie ma za co","Dlaczego?","mieszkać","być","robić (np. zakupy, ćwiczenie)","Ile? (niepoliczalne)","Kiedy?","dawać"},
                                                   {"great","How many?","Who?","What?","know","Where?","How?","speak","you are welcome","Why?","live","be","do","How much?","When?","give"},
                                                   {"genial","¿Cuántos?","¿Quién?","¿Qué?","saber","¿Dónde?","¿Cómo?","hablar","de nada","¿Por qué?","vivir","ser","hacer","¿Cuánto?","¿Cuándo?","dar"} };

        private static string[,] city = {{"ogród","droga","park","pole","stolica","ulica","gospodarstwo","plac","sąsiad","most","miasto","wioska","poczta","tereny wiejskie","kościół","biblioteka","muzeum","bank"},
                                          {"garden","road","park","field","capital","street","farm","square","neighbour","bridge","city","village","post office","countryside","church","library","museum","bank"},
                                          {"el jardín","el camino","el parque","el campo","la capital","la calle","la granja","la plaza","el vecino","el puente","la ciudad","el pueblo","la oficina de correos","el campo","la iglesia","la biblioteca","el museo","el banco"} };

        private static string[,] school = {{"egzamin","ocena","znaczyć","ołówek","książka","szkoła","uczeń","słowo","uczyć","uczyć się","rozumieć","język","matematyka","zdać","nie zdać","historia","geografia","przerwa","pisać","tablica","klasa","długopis","praca domowa","zeszyt","nauczyciel","uniwersytet","ćwiczenie"},
                                            {"exam","mark","mean","pencil","book","school","student","word","teach","learn","understand","language","maths","pass","fail","history","geography","break","write","blackboard","class","pen","homework","copybook","teacher","university","exercise"},
                                            {"el examen","la nota","significar","el lápiz","el libro","la escuela","el alumno","la palabra","enseñar","aprender","entender","el idioma","las matemáticas","aprobar","suspender","la historia","la geografía","el descanso","escribir","la pizarra","la clase","el bolígrafo","los deberes","el cuaderno","el profesor","la universidad","el ejercicio"} };

        private static string[,] appearance = {{"przystojny","stary","młody","ładny","elegancki","wysoki","niski","czysty","prosty","kręcony","brudny","piękny","brzydki","gruby","szczupły"},
                                                {"handsome","old","young","pretty","elegant","tall","short","clean","straight","curly","dirty","beautiful","ugly","fat","slim"},
                                                {"guapo","viejo","joven","bonito","elegante","alto","bajo","limpio","liso","rizado","sucio","hermoso","feo","gordo","delgado"} };

        private static string[,] nature = {{"przyroda","niebo","chmura","słońce","księżyc","jezioro","rzeka","morze","drzewo","liść","kwiat","roślina","trawa","las","góra","gorąco","ciepło","zimno","wiatr","pogoda","deszcz","śnieg","burza"},
                                            {"nature","sky","cloud","sun","moon","lake","river","sea","tree","leaf","flower","plant","grass","forest","mountain","hot","warm","cold","wind","weather","rain","snow","storm"},
                                            {"la naturaleza","el cielo","la nube","el sol","la luna","el lago","el río","el mar","el árbol","la hoja","la flor","la planta","la hierba","el bosque","la montaña","caliente","cálido","frío","el viento","el tiempo","la lluvia","la nieve","la tormenta"} };

        private static string[,] bodyBasic = {{"głowa","włosy","ucho","oko","nos","ząb","usta","twarz","szyja","ramię","brzuch","plecy","ręka","noga","kolano","stopa","palec u nogi","palec u ręki","broda"},
                                               {"head","hair","ear","eye","nose","tooth","lips","face","neck","arm","stomach","back","hand","leg","knee","foot","toe","finger","beard"},
                                               {"la cabeza","el pelo","la oreja","el ojo","la nariz","el diente","los labios","la cara","el cuello","el brazo","el estómago","la espalda","la mano","la pierna","la rodilla","el pie","el dedo del pie","el dedo","la barba"} };

        private static string[,] bodyDetailed = {{"czoło","brew","rzęsy","policzek","podbródek","łokieć","nadgarstek","ramię (bark)","biodro","udo","łydka","kostka","klatka piersiowa","skóra","paznokieć","język","gardło","serce","płuca","mięsień","kość"},
                                                  {"forehead","eyebrow","eyelashes","cheek","chin","elbow","wrist","shoulder","hip","thigh","calf","ankle","chest","skin","nail","tongue","throat","heart","lungs","muscle","bone"},
                                                  {"la frente","la ceja","las pestañas","la mejilla","la barbilla","el codo","la muñeca","el hombro","la cadera","el muslo","la pantorrilla","el tobillo","el pecho","la piel","la uña","la lengua","la garganta","el corazón","los pulmones","el músculo","el hueso"} };

        private static string[,] clothesMaterials = {{"kurtka","skarpetka","pasek","okulary","szalik","rękawiczka","but","spodnie","parasol","koszulka","sukienka","czapka","kapelusz","spódnica","koszula","płaszcz","przymierzać","rozmiar","drewno","metal","plastik","szkło","bawełna","wełna","skóra"},
                                                      {"jacket","sock","belt","glasses","scarf","glove","shoe","trousers","umbrella","T-shirt","dress","cap","hat","skirt","shirt","coat","try on","size","wood","metal","plastic","glass","cotton","wool","leather"},
                                                      {"la chaqueta","el calcetín","el cinturón","las gafas","la bufanda","el guante","el zapato","los pantalones","el paraguas","la camiseta","el vestido","la gorra","el sombrero","la falda","la camisa","el abrigo","probarse","la talla","la madera","el metal","el plástico","el vidrio","el algodón","la lana","el cuero"} };

        private static string[,] countries = {{"Wielka Brytania (Zjednoczone Królestwo)","Japończyk, japoński","Japonia","Rosjanin, rosyjski","Rosja","Kanadyjczyk, kanadyjski","Kanada","Amerykanin, amerykański","Stany Zjednoczone Ameryki","Australijczyk, australijski","Australia","Grek, grecki","Niemiec, niemiecki","Niemcy","Francuz, francuski","Francja","Hiszpan, hiszpański","Hiszpania","Włoch, włoski","Włochy","Polak, polski","Polska","Europa","Azja","narodowość","kraj"},
                                              {"United Kingdom","Japanese","Japan","Russian","Russia","Canadian","Canada","American","United States of America","Australian","Australia","Greek","German","Germany","French","France","Spanish","Spain","Italian","Italy","Polish","Poland","Europe","Asia","nationality","country"},
                                              {"el Reino Unido","japonés","Japón","ruso","Rusia","canadiense","Canadá","estadounidense","los Estados Unidos de América","australiano","Australia","griego","alemán","Alemania","francés","Francia","español","España","italiano","Italia","polaco","Polonia","Europa","Asia","la nacionalidad","el país"} };

        private static string[,] leisureHolidays = {{"relaksować się","śpiewać","pływać","przyjęcie, impreza","bawić się","zainteresowania","robić zdjęcia","wakacje","malować","słuchać","czytać","kino","teatr","koncert","oglądać","uprawiać sporty","biegać","tańczyć","plaża","piasek","fala","kąpiel słoneczna","krem do opalania","opalać się","zamek z piasku"},
                                                     {"relax","sing","swim","party","play","hobbies","take photos","holiday","paint","listen","read","cinema","theatre","concert","watch","do sports","run","dance","beach","sand","wave","sunbathing","sunscreen","to sunbathe","sandcastle"},
                                                     {"relajarse","cantar","nadar","la fiesta","jugar","los intereses","hacer fotos","las vacaciones","pintar","escuchar","leer","el cine","el teatro","el concierto","ver","hacer deporte","correr","bailar","la playa","la arena","la ola","el baño de sol","la crema solar","tomar el sol","el castillo de arena"} };

        private static string[,] sportsMusic = {{"piłka nożna","koszykówka","tenis","pływanie","siatkówka","narciarstwo","jazda konna","gitara","pianino","skrzypce","grać na (instrumencie)","mecz","drużyna","trener"},
                                                 {"football","basketball","tennis","swimming","volleyball","skiing","horse riding","guitar","piano","violin","play (an instrument)","match","team","coach"},
                                                 {"el fútbol","el baloncesto","el tenis","la natación","el voleibol","el esquí","la equitación","la guitarra","el piano","el violín","tocar (un instrumento)","el partido","el equipo","el entrenador"} };

        private static string[,] technologyMedia = {{"internet","hasło","konto","aplikacja","wiadomość","e-mail","link","ładować (telefon)","wifi","strona internetowa","przeglądarka","klikać","logować się","wylogowywać się","pobierać","wysyłać","media społecznościowe","aktualizować","telewizja","radio","gazeta","wiadomości (news)","reklama","program (telewizyjny)"},
                                                     {"internet","password","account","app","message","email","link","charge (phone)","wifi","website","browser","click","log in","log out","download","send","social media","update","television","radio","newspaper","news","advertisement","TV programme"},
                                                     {"el internet","la contraseña","la cuenta","la aplicación","el mensaje","el correo electrónico","el enlace","cargar (el teléfono)","el wifi","el sitio web","el navegador","hacer clic","iniciar sesión","cerrar sesión","descargar","enviar","las redes sociales","actualizar","la televisión","la radio","el periódico","las noticias","el anuncio","el programa"} };

        private static string[,] feelings = {{"zmęczony","bać się","płakać","śmiać się","uśmiechać się","zdenerwowany","senny","zły (na kogoś)","smutny","szczęśliwy","nienawidzić","kochać","lubić","dumny","nudny","zaskakiwać","uczucie","myśleć","martwić się","rozczarowany","zaskoczony","zestresowany","zrelaksowany","zazdrosny"},
                                             {"tired","be scared","cry","laugh","smile","nervous","sleepy","angry","sad","happy","hate","love","like","proud","boring","surprise","feeling","think","worry","disappointed","surprised","stressed","relaxed","jealous"},
                                             {"cansado","tener miedo","llorar","reír","sonreír","nervioso","tener sueño","enfadado","triste","feliz","odiar","amar","gustar","orgulloso","aburrido","sorprender","el sentimiento","pensar","preocuparse","decepcionado","sorprendido","estresado","relajado","celoso"} };

        private static string[,] shopping = {{"portfel","centrum handlowe","księgarnia","piekarnia","drogi","tani","płacić","bankomat","sklep","sprzedawać","pieniądze","targ","cena","koszyk","półka","reszta","kupować","zakupy"},
                                              {"wallet","shopping center","bookshop","bakery","expensive","cheap","pay","cashpoint","shop","sell","money","market","price","basket","shelf","change","buy","shopping"},
                                              {"la cartera","el centro comercial","la librería","la panadería","caro","barato","pagar","el cajero automático","la tienda","vender","el dinero","el mercado","el precio","la cesta","la estantería","el cambio","comprar","las compras"} };

        private static string[,] moneyDining = {{"zamawiać","rachunek","kelner","menu","napiwek","stolik (rezerwacja)","rezerwacja","danie","przystawka","danie główne","konto bankowe","przelew","oszczędzać","pożyczać","rachunek (do zapłacenia)","gotówka","karta kredytowa","karta debetowa","oprocentowanie","kredyt","zadłużenie","wydawać (pieniądze)","budżet","waluta"},
                                                 {"order","bill","waiter","menu","tip","table (reservation)","reservation","dish","starter","main course","bank account","transfer","save (money)","borrow","bill (to pay)","cash","credit card","debit card","interest rate","loan","debt","spend (money)","budget","currency"},
                                                 {"pedir","la cuenta","el camarero","el menú","la propina","la mesa (reserva)","la reserva","el plato","el entrante","el plato principal","la cuenta bancaria","la transferencia","ahorrar","pedir prestado","la factura","el efectivo","la tarjeta de crédito","la tarjeta de débito","el tipo de interés","el préstamo","la deuda","gastar","el presupuesto","la moneda"} };

        private static string[,] professions = {{"muzyk","malarz","naukowiec","policjant","strażak","pielęgniarka","architekt","sekretarka","mechanik","informatyk","programista","inżynier","aktor","artysta","lekarz","dziennikarz","sprzedawca","fryzjer","prawnik"},
                                                 {"musician","painter","scientist","police officer","fireman","nurse","architect","secretary","mechanic","IT specialist","computer programmer","engineer","actor","artist","doctor","journalist","shop assistant","hairdresser","lawyer"},
                                                 {"el músico","el pintor","el científico","el policía","el bombero","la enfermera","el arquitecto","la secretaria","el mecánico","el informático","el programador","el ingeniero","el actor","el artista","el médico","el periodista","el vendedor","el peluquero","el abogado"} };

        private static string[,] officeComputer = {{"dzwonić","kopiować","ekran","plik, dokument","klawiatura","telefon komórkowy","drukować","zapisywać","włączać","wyłączać","praca","biuro","komputer","szef","CV","rozmowa kwalifikacyjna","umowa o pracę","pensja","urlop","zwolnienie (z pracy)","awans","doświadczenie (zawodowe)"},
                                                    {"phone","copy","screen","file","keyboard","mobile phone","print","save","turn on","turn off","work","office","computer","boss","CV","job interview","employment contract","salary","holiday leave","dismissal","promotion","experience"},
                                                    {"llamar","copiar","la pantalla","el archivo","el teclado","el móvil","imprimir","guardar","encender","apagar","el trabajo","la oficina","el ordenador","el jefe","el currículum","la entrevista de trabajo","el contrato de trabajo","el salario","las vacaciones","el despido","el ascenso","la experiencia"} };

        private static string[,] character = {{"arogancki","radosny","nieśmiały","szalony","uparty","inteligentny","spokojny","towarzyski","odważny","miły","sympatyczny","uczciwy","mądry","cierpliwy","samolubny"},
                                               {"rude","cheerful","shy","crazy","stubborn","intelligent","calm","outgoing","brave","nice","friendly","honest","clever","patient","selfish"},
                                               {"arrogante","alegre","tímido","loco","testarudo","inteligente","tranquilo","sociable","valiente","amable","simpático","honesto","listo","paciente","egoísta"} };

        private static string[,] health = {{"pigułka, tabletka","choroba","chory","zdrowy","lekarstwo","karetka","apteka","łamać","kaszel","przeziębić się","grypa","gorączka","umawiać się (na wizytę)","ból","boleć","ból głowy","ból gardła","czuć się","szpital"},
                                            {"pill","illness","sick","healthy","medicine","ambulance","pharmacy","break","cough","catch a cold","flu","fever","make an appointment","pain","hurt","headache","sore throat","feel","hospital"},
                                            {"la pastilla","la enfermedad","enfermo","sano","el medicamento","la ambulancia","la farmacia","romper","la tos","resfriarse","la gripe","la fiebre","pedir cita","el dolor","doler","el dolor de cabeza","el dolor de garganta","sentirse","el hospital"} };

        private static string[,] emergencies = {{"Pomocy!","pożar","niebezpieczeństwo","wzywać (pomoc/policję)","alarm","wypadek","policja","straż pożarna","ratować","uciekać","ostrożnie!","zagrożenie"},
                                                 {"Help!","fire","danger","call (for help/police)","alarm","accident","police","fire brigade","save/rescue","escape","careful!","threat"},
                                                 {"¡Socorro!","el incendio","el peligro","llamar (a la policía)","la alarma","el accidente","la policía","los bomberos","salvar","escapar","¡cuidado!","la amenaza"} };

        private static string[,] celebrations = {{"Boże Narodzenie","Wielkanoc","urodziny","prezent","świętować","życzenia","choinka","fajerwerki","Nowy Rok","imieniny","gratulacje","zapraszać","gość","tort urodzinowy"},
                                                  {"Christmas","Easter","birthday","present","celebrate","wishes","Christmas tree","fireworks","New Year","name day","congratulations","invite","guest","birthday cake"},
                                                  {"la Navidad","la Pascua","el cumpleaños","el regalo","celebrar","los deseos","el árbol de Navidad","los fuegos artificiales","el Año Nuevo","el santo","las felicidades","invitar","el invitado","la tarta de cumpleaños"} };

        private static string[,] verbsActions = {{"potrzebować","szukać","znajdować","pomagać","zaczynać","kończyć","kontynuować","przestawać","pamiętać","zapominać","próbować","wyjaśniać","pytać","odpowiadać","wybierać","decydować się","obiecywać","mieć nadzieję"},
                                                  {"need","look for","find","help","start","finish","continue","stop","remember","forget","try","explain","ask","answer","choose","decide","promise","hope"},
                                                  {"necesitar","buscar","encontrar","ayudar","empezar","terminar","continuar","parar","recordar","olvidar","intentar","explicar","preguntar","responder","elegir","decidir","prometer","esperar"} };

        private static string[][,] kategorie = { numbers, wordsMath, colors, animalsHome, animalsWild, animalWords, kitchen, bathroom, livingBedroom, buildingGeneral,
												vegetables, fruits, farmCrops, soups };
    }
}